# **The nutrients of the ingredients**

## Configuration:

Import necessary entities:

In [1]:
import os
import sys

sys.path.append(
    os.path.abspath(
        os.path.join(
            os.getcwd(),
            os.pardir,
        ),
    ),
)

from json import load
from typing import Any
from pandas import (
    DataFrame,
    read_csv,
    set_option,
)

from src.models.fdc import FDC

Prepare *Pandas* dataframe output:

In [2]:
set_option("display.width", 120, )
set_option("display.max_columns", None, )
set_option("display.expand_frame_repr", False, )

## Preprocessing:

Create a dictionary for `load()` function calling:

In [3]:
load_json_params: dict[str, str] = {
    "file": "food.json",

    "file_path": "../data/json/",
}

Read the file `food.json` data:

In [4]:
with open(
    encoding="utf-8",
    file=load_json_params["file_path"] + load_json_params["file"],
) as file:
    food_data: dict[str, list[str]] = load(file, )
    ingredients: list[str] = food_data["ingredients"]

Check `ingredients` list:

In [5]:
ingredients

['cod',
 'fig',
 'egg',
 'gin',
 'ham',
 'oat',
 'nut',
 'pea',
 'rum',
 'rye',
 'soy',
 'tea',
 'sage',
 'port',
 'date',
 'beef',
 'beet',
 'beer',
 'bran',
 'brie',
 'bass',
 'crab',
 'bean',
 'clam',
 'feta',
 'duck',
 'corn',
 'dill',
 'kiwi',
 'leek',
 'lime',
 'kale',
 'mint',
 'pear',
 'orzo',
 'plum',
 'okra',
 'pork',
 'seed',
 'sake',
 'rice',
 'tofu',
 'tuna',
 'veal',
 'yuca',
 'wine',
 'lamb',
 'apple',
 'basil',
 'bread',
 'bacon',
 'chive',
 'chard',
 'chile',
 'curry',
 'clove',
 'cumin',
 'anise',
 'grape',
 'honey',
 'goose',
 'guava',
 'mango',
 'lemon',
 'melon',
 'olive',
 'peach',
 'pecan',
 'pasta',
 'onion',
 'poppy',
 'prune',
 'quail',
 'squid',
 'thyme',
 'trout',
 'vodka',
 'midori',
 'almond',
 'barley',
 'brandy',
 'cashew',
 'celery',
 'carrot',
 'caviar',
 'capers',
 'bulgur',
 'butter',
 'cherry',
 'banana',
 'coffee',
 'endive',
 'fennel',
 'garlic',
 'lentil',
 'hummus',
 'kirsch',
 'ginger',
 'lychee',
 'mussel',
 'mezcal',
 'orange',
 'peanut',
 'papaya',
 'pernod',
 'nutmeg',
 'oyster',
 'rabbit',
 'noodle',
 'radish',
 'quinoa',
 'raisin',
 'quince',
 'potato',
 'scotch',
 'salmon',
 'pepper',
 'sherry',
 'spirit',
 'tomato',
 'turnip',
 'sesame',
 'shrimp',
 'waffle',
 'walnut',
 'wasabi',
 'yogurt',
 'turkey',
 'pickles',
 'snapper',
 'granola',
 'kumquat',
 'apricot',
 'arugula',
 'avocado',
 'bourbon',
 'cabbage',
 'caraway',
 'anchovy',
 'cheddar',
 'buffalo',
 'chicken',
 'brownie',
 'coconut',
 'currant',
 'fontina',
 'egg nog',
 'custard',
 'halibut',
 'lettuce',
 'lobster',
 'liqueur',
 'mustard',
 'martini',
 'oatmeal',
 'oregano',
 'octopus',
 'parsley',
 'parsnip',
 'paprika',
 'marsala',
 'pumpkin',
 'ricotta',
 'saffron',
 'sangria',
 'scallop',
 'sardine',
 'sausage',
 'rhubarb',
 'shallot',
 'tequila',
 'poblano',
 'spinach',
 'tapioca',
 'tilapia',
 'venison',
 'vanilla',
 'whiskey',
 'vinegar',
 'chambord',
 'aperitif',
 'bok choy',
 'beef rib',
 'broccoli',
 'calvados',
 'amaretto',
 'cardamom',
 'cilantro',
 'couscous',
 'chickpea',
 'chestnut',
 'eggplant',
 'cinnamon',
 'cornmeal',
 'escarole',
 'cucumber',
 'hazelnut',
 'honeydew',
 'jalapeño',
 'mushroom',
 'molasses',
 'parmesan',
 'pine nut',
 'pork rib',
 'rutabaga',
 'plantain',
 'rosemary',
 'semolina',
 'red wine',
 'spritzer',
 'tree nut',
 'tarragon',
 'vermouth',
 'tamarind',
 'zucchini',
 'champagne',
 'artichoke',
 'asparagus',
 'chocolate',
 'cranberry',
 'blueberry',
 'coriander',
 'lamb chop',
 'lima bean',
 'persimmon',
 'nectarine',
 'radicchio',
 'pork chop',
 'pistachio',
 'raspberry',
 'pineapple',
 'sourdough',
 'tomatillo',
 'tangerine',
 'wild rice',
 'soy sauce',
 'shellfish',
 'swordfish',
 'sour cream',
 'asian pear',
 'blackberry',
 'beef shank',
 'buttermilk',
 'brown rice',
 'chartreuse',
 'eau de vie',
 'frangelico',
 'cantaloupe',
 'grapefruit',
 'hot pepper',
 'green bean',
 'lamb shank',
 'lemongrass',
 'lime juice',
 'mozzarella',
 'mayonnaise',
 'strawberry',
 'watermelon',
 'watercress',
 'sesame oil',
 'white wine',
 'apple juice',
 'breadcrumbs',
 'bell pepper',
 'blue cheese',
 'cauliflower',
 'ground beef',
 'horseradish',
 'ground lamb',
 'goat cheese',
 'lingonberry',
 'maple syrup',
 'lemon juice',
 'marshmallow',
 'pomegranate',
 'chile pepper',
 'cream cheese',
 'jam or jelly',
 'orange juice',
 'rack of lamb',
 'swiss cheese',
 'broccoli rabe',
 'macadamia nut',
 'grand marnier',
 'monterey jack',
 'peanut butter',
 'passion fruit',
 'yellow squash',
 'mustard greens',
 'cottage cheese',
 'créme de cacao',
 'collard greens',
 'brussel sprout',
 'fortified wine',
 'sparkling wine',
 'sugar snap pea',
 'beef tenderloin',
 'cranberry sauce',
 'pork tenderloin',
 'poultry sausage',
 'pomegranate juice',
 'jerusalem artichoke',
 'hominy/cornmeal/masa']

Create a `Food Data Central` representative:

In [6]:
fdc: FDC = FDC()

## The nutrients of the ingredients:

Fetch ingredients data:

In [7]:
ingredients_data: list[
    dict[str, Any] | None
] = await fdc.fetch_ingredients_data(ingredients, )

Check `ingredients_data` list:

In [8]:
ingredients_data

[{'totalHits': 813,
  'currentPage': 1,
  'totalPages': 813,
  'pageList': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
  'foodSearchCriteria': {'query': 'cod',
   'generalSearchInput': 'cod',
   'pageNumber': 1,
   'numberOfResultsPerPage': 50,
   'pageSize': 1,
   'requireAllWords': False},
  'foods': [{'fdcId': 2099857,
    'description': 'COD',
    'dataType': 'Branded',
    'gtinUpc': '015292210037',
    'publishedDate': '2021-10-28',
    'brandOwner': "Morey's Seafood International",
    'brandName': "MOREY'S",
    'ingredients': 'COD, WATER, SUN-DRIED TOMATOES, BLACK OLIVES, PARMESAN CHEESE (PARTIALLY SKIM MILK, CULTURES, SALT, ENZYMES), MODIFIED CORN STARCH, SALT, DEHYDRATED GARLIC, CORN SYRUP SOLIDS, TOMATO POWDER, DEHYDRATED TOMATO, DEHYDRATED PARSLEY, MALTODEXTRIN, DEHYDRATED SUN-DRIED TOMATO, LEMON JUICE, GUAR GUM, NATURAL FLAVOR, OLIVE OIL BLEND (CANOLA OIL AND OLIVE OIL), BASIL, POTATO STARCH.',
    'marketCountry': 'United States',
    'foodCategory': 'Frozen Fish & Seafood',
    'modifiedDate': '2018-09-20',
    'dataSource': 'LI',
    'packageWeight': '12 oz/340 g',
    'servingSizeUnit': 'g',
    'servingSize': 170.0,
    'householdServingFullText': '6 ONZ',
    'tradeChannels': ['NO_TRADE_CHANNEL'],
    'allHighlightFields': '<b>Ingredients</b>: <em>COD</em>, WATER, SUN-DRIED TOMATOES, BLACK OLIVES, PARMESAN CHEESE (PARTIALLY SKIM MILK, CULTURES, SALT',
    'score': 1337.5688,
    'microbes': [],
    'foodNutrients': [{'nutrientId': 1003,
      'nutrientName': 'Protein',
      'nutrientNumber': '203',
      'unitName': 'G',
      'derivationCode': 'LCCS',
      'derivationDescription': 'Calculated from value per serving size measure',
      'derivationId': 70,
      'value': 12.4,
      'foodNutrientSourceId': 9,
      'foodNutrientSourceCode': '12',
      'foodNutrientSourceDescription': "Manufacturer's analytical; partial documentation",
      'rank': 600,
      'indentLevel': 1,
      'foodNutrientId': 25836253},
     {'nutrientId': 1004,
      'nutrientName': 'Total lipid (fat)',
      'nutrientNumber': '204',
      'unitName': 'G',
      'derivationCode': 'LCCS',
      'derivationDescription': 'Calculated from value per serving size measure',
      'derivationId': 70,
      'value': 2.94,
      'foodNutrientSourceId': 9,
      'foodNutrientSourceCode': '12',
      'foodNutrientSourceDescription': "Manufacturer's analytical; partial documentation",
      'rank': 800,
      'indentLevel': 1,
      'foodNutrientId': 25836254,
      'percentDailyValue': 8},
     {'nutrientId': 1005,
      'nutrientName': 'Carbohydrate, by difference',
      'nutrientNumber': '205',
      'unitName': 'G',
      'derivationCode': 'LCCS',
      'derivationDescription': 'Calculated from value per serving size measure',
      'derivationId': 70,
      'value': 5.29,
      'foodNutrientSourceId': 9,
      'foodNutrientSourceCode': '12',
      'foodNutrientSourceDescription': "Manufacturer's analytical; partial documentation",
      'rank': 1110,
      'indentLevel': 2,
      'foodNutrientId': 25836255,
      'percentDailyValue': 3},
     {'nutrientId': 1008,
      'nutrientName': 'Energy',
      'nutrientNumber': '208',
      'unitName': 'KCAL',
      'derivationCode': 'LCCS',
      'derivationDescription': 'Calculated from value per serving size measure',
      'derivationId': 70,
      'value': 100,
      'foodNutrientSourceId': 9,
      'foodNutrientSourceCode': '12',
      'foodNutrientSourceDescription': "Manufacturer's analytical; partial documentation",
      'rank': 300,
      'indentLevel': 1,
      'foodNutrientId': 25836256},
     {'nutrientId': 2000,
      'nutrientName': 'Total Sugars',
      'nutrientNumber': '269',
      'unitName': 'G',
      'derivationCode': 'LCCS',
      'derivationDescription': 'Calculated from value per serving size measure',
      'derivationId': 70,
      'value': 0.0,
      'foodNutrientSourceId': 9,
      'foodNutrientSourceCode': '12',
      'foodNutrientSourceDescription': "Manufacturer's analytical; partial documentation",
      'rank': 1510,
      'indentLevel': 3,
      'foodNutrientId': 25836257},
     {'nutrientId': 1079,
      'nutrientName': 'Fiber, total dietary',
      'nutrientNumber': '291',
      'unitName': 'G',
      'derivationCode': 'LCCS',
      'derivationDescription': 'Calculated from value per serving size measure',
      'derivationId': 70,
      'value': 0.6,
      'foodNutrientSourceId': 9,
      'foodNutrientSourceCode': '12',
      'foodNutrientSourceDescription': "Manufacturer's analytical; partial documentation",
      'rank': 1200,
      'indentLevel': 3,
      'foodNutrientId': 25836258,
      'percentDailyValue': 4},
     {'nutrientId': 1087,
      'nutrientName': 'Calcium, Ca',
      'nutrientNumber': '301',
      'unitName': 'MG',
      'derivationCode': 'LCCD',
      'derivationDescription': 'Calculated from a daily value percentage per serving size measure',
      'derivationId': 75,
      'value': 35.0,
      'foodNutrientSourceId': 9,
      'foodNutrientSourceCode': '12',
      'foodNutrientSourceDescription': "Manufacturer's analytical; partial documentation",
      'rank': 5300,
      'indentLevel': 1,
      'foodNutrientId': 25836259,
      'percentDailyValue': 6},
     {'nutrientId': 1089,
      'nutrientName': 'Iron, Fe',
      'nutrientNumber': '303',
      'unitName': 'MG',
      'derivationCode': 'LCCD',
      'derivationDescription': 'Calculated from a daily value percentage per serving size measure',
      'derivationId': 75,
      'value': 0.85,
      'foodNutrientSourceId': 9,
      'foodNutrientSourceCode': '12',
      'foodNutrientSourceDescription': "Manufacturer's analytical; partial documentation",
      'rank': 5400,
      'indentLevel': 1,
      'foodNutrientId': 25836260,
      'percentDailyValue': 8},
     {'nutrientId': 1093,
      'nutrientName': 'Sodium, Na',
      'nutrientNumber': '307',
      'unitName': 'MG',
      'derivationCode': 'LCCS',
      'derivationDescription': 'Calculated from value per serving size measure',
      'derivationId': 70,
      'value': 418,
      'foodNutrientSourceId': 9,
      'foodNutrientSourceCode': '12',
      'foodNutrientSourceDescription': "Manufacturer's analytical; partial documentation",
      'rank': 5800,
      'indentLevel': 1,
      'foodNutrientId': 25836261,
      'percentDailyValue': 30},
     {'nutrientId': 1104,
      'nutrientName': 'Vitamin A, IU',
      'nutrientNumber': '318',
      'unitName': 'IU',
      'derivationCode': 'LCCD',
      'derivationDescription': 'Calculated from a daily value percentage per serving size measure',
      'derivationId': 75,
      'value': 118,
      'foodNutrientSourceId': 9,
      'foodNutrientSourceCode': '12',
      'foodNutrientSourceDescription': "Manufacturer's analytical; partial documentation",
      'rank': 7500,
      'indentLevel': 1,
      'foodNutrientId': 25836262,
      'percentDailyValue': 4},
     {'nutrientId': 1162,
      'nutrientName': 'Vitamin C, total ascorbic acid',
      'nutrientNumber': '401',
      'unitName': 'MG',
      'derivationCode': 'LCCD',
      'derivationDescription': 'Calculated from a daily value percentage per serving size measure',
      'derivationId': 75,
      'value': 3.5,
      'foodNutrientSourceId': 9,
      'foodNutrientSourceCode': '12',
      'foodNutrientSourceDescription': "Manufacturer's analytical; partial documentation",
      'rank': 6300,
      'indentLevel': 1,
      'foodNutrientId': 25836263,
      'percentDailyValue': 10},
     {'nutrientId': 1253,
      'nutrientName': 'Cholesterol',
      'nutrientNumber': '601',
      'unitName': 'MG',
      'derivationCode': 'LCCS',
      'derivationDescription': 'Calculated from value per serving size measure',
      'derivationId': 70,
      'value': 32.0,
      'foodNutrientSourceId': 9,
      'foodNutrientSourceCode': '12',
      'foodNutrientSourceDescription': "Manufacturer's analytical; partial documentation",
      'rank': 15700,
      'indentLevel': 1,
      'foodNutrientId': 25836264,
      'percentDailyValue': 18},
     {'nutrientId': 1257,
      'nutrientName': 'Fatty acids, total trans',
      'nutrientNumber': '605',
      'unitName': 'G',
      'derivationCode': 'LCCS',
      'derivationDescription': 'Calculated from value per serving size measure',
      'derivationId': 70,
      'value': 0.0,
      'foodNutrientSourceId': 9,
      'foodNutrientSourceCode': '12',
      'foodNutrientSourceDescription': "Manufacturer's analytical; partial documentation",
      'rank': 15400,
      'indentLevel': 1,
      'foodNutrientId': 25836265},
     {'nutrientId': 1258,
      'nutrientName': 'Fatty acids, total saturated',
      'nutrientNumber': '606',
      'unitName': 'G',
      'derivationCode': 'LCCS',
      'derivationDescription': 'Calculated from value per serving size measure',
      'derivationId': 70,
      'value': 0.59,
      'foodNutrientSourceId': 9,
      'foodNutrientSourceCode': '12',
      'foodNutrientSourceDescription': "Manufacturer's analytical; partial documentation",
      'rank': 9700,
      'indentLevel': 1,
      'foodNutrientId': 25836266,
      'percentDailyValue': 5}],
    'finalFoodInputFoods': [],
    'foodMeasures': [],
    'foodAttributes': [],
    'foodAttributeTypes': [],
    'foodVersionIds': []}],
  'aggregations': {'dataType': {'Branded': 797,
    'SR Legacy': 8,
    'Survey (FNDDS)': 7,
    'Foundation': 1},
   'nutrients': {}}},
 {'totalHits': 962,
  'currentPage': 1,
  'totalPages': 962,
  'pageList': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
  'foodSearchCriteria': {'query': 'fig',
   'generalSearchInput': 'fig',
   'pageNumber': 1,
   'numberOfResultsPerPage': 50,
   'pageSize': 1,
   'requireAllWords': False},
  'foods': [{'fdcId': 2216672,
    'description': 'FIG',
    'dataType': 'Branded',
    'gtinUpc': '616618500094',
    'publishedDate': '2022-01-06',
    'brandOwner': 'Adria Imports Inc.',
    'brandName': 'MARCO POLO',
    'ingredients': 'FIGS, SUGAR, CITRIC ACID, PECTIN.',
    'marketCountry': 'United States',
    'foodCategory': 'Jam, Jelly & Fruit Spreads',
    'modifiedDate': '2021-11-13',
    'dataSource': 'LI',
    'packageWeight': '13 oz/368 g',
    'servingSizeUnit': 'g',
    'servingSize': 20.0,
    'householdServingFullText': '1 Tbsp',
    'tradeChannels': ['NO_TRADE_CHANNEL'],
    'allHighlightFields': '<b>Ingredients</b>: <em>FIGS</em>, SUGAR, CITRIC ACID, PECTIN.',
    'score': 1312.3948,
    'microbes': [],
    'foodNutrients': [{'nutrientId': 1003,
      'nutrientName': 'Protein',
      'nutrientNumber': '203',
      'unitName': 'G',
      'derivationCode': 'LCCS',
      'derivationDescription': 'Calculated from value per serving size measure',
      'derivationId': 70,
      'value': 0.0,
      'foodNutrientSourceId': 9,
      'foodNutrientSourceCode': '12',
      'foodNutrientSourceDescription': "Manufacturer's analytical; partial documentation",
      'rank': 600,
      'indentLevel': 1,
      'foodNutrientId': 27281048},
     {'nutrientId': 1004,
      'nutrientName': 'Total lipid (fat)',
      'nutrientNumber': '204',
      'unitName': 'G',
      'derivationCode': 'LCCD',
      'derivationDescription': 'Calculated from a daily value percentage per serving size measure',
      'derivationId': 75,
      'value': 0.0,
      'foodNutrientSourceId': 9,
      'foodNutrientSourceCode': '12',
      'foodNutrientSourceDescription': "Manufacturer's analytical; partial documentation",
      'rank': 800,
      'indentLevel': 1,
      'foodNutrientId': 27281049,
      'percentDailyValue': 0},
     {'nutrientId': 1005,
      'nutrientName': 'Carbohydrate, by difference',
      'nutrientNumber': '205',
      'unitName': 'G',
      'derivationCode': 'LCCS',
      'derivationDescription': 'Calculated from value per serving size measure',
      'derivationId': 70,
      'value': 65.0,
      'foodNutrientSourceId': 9,
      'foodNutrientSourceCode': '12',
      'foodNutrientSourceDescription': "Manufacturer's analytical; partial documentation",
      'rank': 1110,
      'indentLevel': 2,
      'foodNutrientId': 27281050,
      'percentDailyValue': 4},
     {'nutrientId': 1008,
      'nutrientName': 'Energy',
      'nutrientNumber': '208',
      'unitName': 'KCAL',
      'derivationCode': 'LCCS',
      'derivationDescription': 'Calculated from value per serving size measure',
      'derivationId': 70,
      'value': 250,
      'foodNutrientSourceId': 9,
      'foodNutrientSourceCode': '12',
      'foodNutrientSourceDescription': "Manufacturer's analytical; partial documentation",
      'rank': 300,
      'indentLevel': 1,
      'foodNutrientId': 27281051},
     {'nutrientId': 2000,
      'nutrientName': 'Total Sugars',
      'nutrientNumber': '269',
      'unitName': 'G',
      'derivationCode': 'LCCS',
      'derivationDescription': 'Calculated from value per serving size measure',
      'derivationId': 70,
      'value': 65.0,
      'foodNutrientSourceId': 9,
      'foodNutrientSourceCode': '12',
      'foodNutrientSourceDescription': "Manufacturer's analytical; partial documentation",
      'rank': 1510,
      'indentLevel': 3,
      'foodNutrientId': 27281052},
     {'nutrientId': 1079,
      'nutrientName': 'Fiber, total dietary',
      'nutrientNumber': '291',
      'unitName': 'G',
      'derivationCode': 'LCCD',
      'derivationDescription': 'Calculated from a daily value percentage per serving size measure',
      'derivationId': 75,
      'value': 0.0,
      'foodNutrientSourceId': 9,
      'foodNutrientSourceCode': '12',
      'foodNutrientSourceDescription': "Manufacturer's analytical; partial documentation",
      'rank': 1200,
      'indentLevel': 3,
      'foodNutrientId': 27281053,
      'percentDailyValue': 0},
     {'nutrientId': 1087,
      'nutrientName': 'Calcium, Ca',
      'nutrientNumber': '301',
      'unitName': 'MG',
      'derivationCode': 'LCCS',
      'derivationDescription': 'Calculated from value per serving size measure',
      'derivationId': 70,
      'value': 15.0,
      'foodNutrientSourceId': 9,
      'foodNutrientSourceCode': '12',
      'foodNutrientSourceDescription': "Manufacturer's analytical; partial documentation",
      'rank': 5300,
      'indentLevel': 1,
      'foodNutrientId': 27281054,
      'percentDailyValue': 0},
     {'nutrientId': 1089,
      'nutrientName': 'Iron, Fe',
      'nutrientNumber': '303',
      'unitName': 'MG',
      'derivationCode': 'LCCD',
      'derivationDescription': 'Calculated from a daily value percentage per serving size measure',
      'derivationId': 75,
      'value': 0.0,
      'foodNutrientSourceId': 9,
      'foodNutrientSourceCode': '12',
      'foodNutrientSourceDescription': "Manufacturer's analytical; partial documentation",
      'rank': 5400,
      'indentLevel': 1,
      'foodNutrientId': 27281055,
      'percentDailyValue': 0},
     {'nutrientId': 1092,
      'nutrientName': 'Potassium, K',
      'nutrientNumber': '306',
      'unitName': 'MG',
      'derivationCode': 'LCCS',
      'derivationDescription': 'Calculated from value per serving size measure',
      'derivationId': 70,
      'value': 105,
      'foodNutrientSourceId': 9,
      'foodNutrientSourceCode': '12',
      'foodNutrientSourceDescription': "Manufacturer's analytical; partial documentation",
      'rank': 5700,
      'indentLevel': 1,
      'foodNutrientId': 27281056,
      'percentDailyValue': 1},
     {'nutrientId': 1093,
      'nutrientName': 'Sodium, Na',
      'nutrientNumber': '307',
      'unitName': 'MG',
      'derivationCode': 'LCCS',
      'derivationDescription': 'Calculated from value per serving size measure',
      'derivationId': 70,
      'value': 5.0,
      'foodNutrientSourceId': 9,
      'foodNutrientSourceCode': '12',
      'foodNutrientSourceDescription': "Manufacturer's analytical; partial documentation",
      'rank': 5800,
      'indentLevel': 1,
      'foodNutrientId': 27281057,
      'percentDailyValue': 0},
     {'nutrientId': 1110,
      'nutrientName': 'Vitamin D (D2 + D3), International Units',
      'nutrientNumber': '324',
      'unitName': 'IU',
      'derivationCode': 'LCCD',
      'derivationDescription': 'Calculated from a daily value percentage per serving size measure',
      'derivationId': 75,
      'value': 0.0,
      'foodNutrientSourceId': 9,
      'foodNutrientSourceCode': '12',
      'foodNutrientSourceDescription': "Manufacturer's analytical; partial documentation",
      'rank': 8650,
      'indentLevel': 1,
      'foodNutrientId': 27281058,
      'percentDailyValue': 0},
     {'nutrientId': 1235,
      'nutrientName': 'Sugars, added',
      'nutrientNumber': '539',
      'unitName': 'G',
      'derivationCode': 'LCCS',
      'derivationDescription': 'Calculated from value per serving size measure',
      'derivationId': 70,
      'value': 60.0,
      'foodNutrientSourceId': 9,
      'foodNutrientSourceCode': '12',
      'foodNutrientSourceDescription': "Manufacturer's analytical; partial documentation",
      'rank': 1540,
      'indentLevel': 0,
      'foodNutrientId': 27281059,
      'percentDailyValue': 24},
     {'nutrientId': 1253,
      'nutrientName': 'Cholesterol',
      'nutrientNumber': '601',
      'unitName': 'MG',
      'derivationCode': 'LCCD',
      'derivationDescription': 'Calculated from a daily value percentage per serving size measure',
      'derivationId': 75,
      'value': 0.0,
      'foodNutrientSourceId': 9,
      'foodNutrientSourceCode': '12',
      'foodNutrientSourceDescription': "Manufacturer's analytical; partial documentation",
      'rank': 15700,
      'indentLevel': 1,
      'foodNutrientId': 27281060,
      'percentDailyValue': 0},
     {'nutrientId': 1257,
      'nutrientName': 'Fatty acids, total trans',
      'nutrientNumber': '605',
      'unitName': 'G',
      'derivationCode': 'LCCS',
      'derivationDescription': 'Calculated from value per serving size measure',
      'derivationId': 70,
      'value': 0.0,
      'foodNutrientSourceId': 9,
      'foodNutrientSourceCode': '12',
      'foodNutrientSourceDescription': "Manufacturer's analytical; partial documentation",
      'rank': 15400,
      'indentLevel': 1,
      'foodNutrientId': 27281061},
     {'nutrientId': 1258,
      'nutrientName': 'Fatty acids, total saturated',
      'nutrientNumber': '606',
      'unitName': 'G',
      'derivationCode': 'LCCD',
      'derivationDescription': 'Calculated from a daily value percentage per serving size measure',
      'derivationId': 75,
      'value': 0.0,
      'foodNutrientSourceId': 9,
      'foodNutrientSourceCode': '12',
      'foodNutrientSourceDescription': "Manufacturer's analytical; partial documentation",
      'rank': 9700,
      'indentLevel': 1,
      'foodNutrientId': 27281062,
      'percentDailyValue': 0}],
    'finalFoodInputFoods': [],
    'foodMeasures': [],
    'foodAttributes': [],
    'foodAttributeTypes': [],
    'foodVersionIds': []}],
  'aggregations': {'dataType': {'Branded': 949,
    'SR Legacy': 8,
    'Survey (FNDDS)': 4,
    'Foundation': 1},
   'nutrients': {}}},
 {'totalHits': 51402,
  'currentPage': 1,
  'totalPages': 51402,
  'pageList': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
  'foodSearchCriteria': {'query': 'egg',
   'generalSearchInput': 'egg',
   'pageNumber': 1,
   'numberOfResultsPerPage': 50,
   'pageSize': 1,
   'requireAllWords': False},
  'foods': [{'fdcId': 2575290,
    'description': 'EGG',
    'dataType': 'Branded',
    'gtinUpc': '040000449270',
    'publishedDate': '2023-06-29',
    'brandOwner': 'Mars Chocolate North America LLC',
    'brandName': 'SNICKERS',
    'ingredients': 'MILK CHOCOLATE (SUGAR, COCOA BUTTER, CHOCOLATE, SKIM MILK, LACTOSE, MILKFAT, SOY LECITHIN, ARTIFICIAL FLAVOR), PEANUTS, SUGAR, INVERT SUGAR, HYDROGENATED PALM KERNEL OIL AND/OR PALM OIL, CORN SYRUP, SKIM MILK, LESS THAN 2% - BUTTER, MILKFAT, PARTIALLY HYDROGENATED SOYBEAN OIL, SALT, SOY LECITHIN, POTASSIUM SORBATE TO MAINTAIN FRESHNESS, ARTIFICIAL FLAVOR.',
    'marketCountry': 'United States',
    'foodCategory': 'Candy',

Parse ingredients nutrients data:

In [9]:
ingredients_nutrients_data: list[
    list[list[str | None, float, str]]
] = FDC.parse_ingredients_nutrients_data(ingredients_data, )

Check `ingredients_nutrients_data` list:

In [10]:
ingredients_nutrients_data

[[['Protein', 12.4, 'G'],
  ['Total lipid (fat)', 2.94, 'G'],
  ['Carbohydrate, by difference', 5.29, 'G'],
  ['Energy', 100, 'KCAL'],
  ['Total Sugars', 0.0, 'G'],
  ['Fiber, total dietary', 0.6, 'G'],
  ['Calcium, Ca', 35.0, 'MG'],
  ['Iron, Fe', 0.85, 'MG'],
  ['Sodium, Na', 418, 'MG'],
  ['Vitamin A, IU', 118, 'IU'],
  ['Vitamin C, total ascorbic acid', 3.5, 'MG'],
  ['Cholesterol', 32.0, 'MG'],
  ['Fatty acids, total trans', 0.0, 'G'],
  ['Fatty acids, total saturated', 0.59, 'G']],
 [['Protein', 0.0, 'G'],
  ['Total lipid (fat)', 0.0, 'G'],
  ['Carbohydrate, by difference', 65.0, 'G'],
  ['Energy', 250, 'KCAL'],
  ['Total Sugars', 65.0, 'G'],
  ['Fiber, total dietary', 0.0, 'G'],
  ['Calcium, Ca', 15.0, 'MG'],
  ['Iron, Fe', 0.0, 'MG'],
  ['Potassium, K', 105, 'MG'],
  ['Sodium, Na', 5.0, 'MG'],
  ['Vitamin D (D2 + D3), International Units', 0.0, 'IU'],
  ['Sugars, added', 60.0, 'G'],
  ['Cholesterol', 0.0, 'MG'],
  ['Fatty acids, total trans', 0.0, 'G'],
  ['Fatty acids, total saturated', 0.0, 'G']],
 [['Protein', 6.41, 'G'],
  ['Total lipid (fat)', 28.8, 'G'],
  ['Carbohydrate, by difference', 57.7, 'G'],
  ['Energy', 513, 'KCAL'],
  ['Total Sugars', 54.5, 'G'],
  ['Fiber, total dietary', 3.2, 'G'],
  ['Calcium, Ca', 128, 'MG'],
  ['Iron, Fe', 0.0, 'MG'],
  ['Sodium, Na', 176, 'MG'],
  ['Vitamin C, total ascorbic acid', 0.0, 'MG'],
  ['Cholesterol', 32.0, 'MG'],
  ['Fatty acids, total trans', 0.0, 'G'],
  ['Fatty acids, total saturated', 16.0, 'G'],
  ['Vitamin A, RAE', 0.0, 'UG']],
 [['Protein', 0, 'G'],
  ['Total lipid (fat)', 0, 'G'],
  ['Carbohydrate, by difference', 0, 'G'],
  ['Energy', 231, 'KCAL'],
  ['Alcohol, ethyl', 33.4, 'G'],
  ['Water', 66.6, 'G'],
  ['Caffeine', 0, 'MG'],
  ['Theobromine', 0, 'MG'],
  ['Total Sugars', 0, 'G'],
  ['Fiber, total dietary', 0, 'G'],
  ['Calcium, Ca', 0, 'MG'],
  ['Iron, Fe', 0.04, 'MG'],
  ['Magnesium, Mg', 0, 'MG'],
  ['Phosphorus, P', 4, 'MG'],
  ['Potassium, K', 2, 'MG'],
  ['Sodium, Na', 1, 'MG'],
  ['Zinc, Zn', 0.04, 'MG'],
  ['Copper, Cu', 0.021, 'MG'],
  ['Selenium, Se', 0, 'UG'],
  ['Retinol', 0, 'UG'],
  ['Vitamin A, RAE', 0, 'UG'],
  ['Carotene, beta', 0, 'UG'],
  ['Carotene, alpha', 0, 'UG'],
  ['Vitamin E (alpha-tocopherol)', 0, 'MG'],
  ['Vitamin D (D2 + D3)', 0, 'UG'],
  ['Cryptoxanthin, beta', 0, 'UG'],
  ['Lycopene', 0, 'UG'],
  ['Lutein + zeaxanthin', 0, 'UG'],
  ['Vitamin C, total ascorbic acid', 0, 'MG'],
  ['Thiamin', 0.006, 'MG'],
  ['Riboflavin', 0.004, 'MG'],
  ['Niacin', 0.013, 'MG'],
  ['Vitamin B-6', 0.001, 'MG'],
  ['Folate, total', 0, 'UG'],
  ['Vitamin B-12', 0, 'UG'],
  ['Choline, total', 0, 'MG'],
  ['Vitamin K (phylloquinone)', 0, 'UG'],
  ['Folic acid', 0, 'UG'],
  ['Folate, food', 0, 'UG'],
  ['Folate, DFE', 0, 'UG'],
  ['Vitamin E, added', 0, 'MG'],
  ['Vitamin B-12, added', 0, 'UG'],
  ['Cholesterol', 0, 'MG'],
  ['Fatty acids, total saturated', 0, 'G'],
  ['SFA 4:0', 0, 'G'],
  ['SFA 6:0', 0, 'G'],
  ['SFA 8:0', 0, 'G'],
  ['SFA 10:0', 0, 'G'],
  ['SFA 12:0', 0, 'G'],
  ['SFA 14:0', 0, 'G'],
  ['SFA 16:0', 0, 'G'],
  ['SFA 18:0', 0, 'G'],
  ['MUFA 18:1', 0, 'G'],
  ['PUFA 18:2', 0, 'G'],
  ['PUFA 18:3', 0, 'G'],
  ['PUFA 20:4', 0, 'G'],
  ['PUFA 22:6 n-3 (DHA)', 0, 'G'],
  ['MUFA 16:1', 0, 'G'],
  ['PUFA 18:4', 0, 'G'],
  ['MUFA 20:1', 0, 'G'],
  ['PUFA 20:5 n-3 (EPA)', 0, 'G'],
  ['MUFA 22:1', 0, 'G'],
  ['PUFA 22:5 n-3 (DPA)', 0, 'G'],
  ['Fatty acids, total monounsaturated', 0, 'G'],
  ['Fatty acids, total polyunsaturated', 0, 'G']],
 [['Protein', 19.04, 'G'],
  ['Total lipid (fat)', 3.87, 'G'],
  ['Carbohydrate, by difference', 1.58, 'G'],
  ['Energy', 117, 'KCAL'],
  ['Alcohol, ethyl', 0, 'G'],
  ['Water', 71.89, 'G'],
  ['Caffeine', 0, 'MG'],
  ['Theobromine', 0, 'MG'],
  ['Total Sugars', 1.54, 'G'],
  ['Fiber, total dietary', 0, 'G'],
  ['Calcium, Ca', 8, 'MG'],
  ['Iron, Fe', 0.84, 'MG'],
  ['Magnesium, Mg', 20, 'MG'],
  ['Phosphorus, P', 276, 'MG'],
  ['Potassium, K', 371, 'MG'],
  ['Sodium, Na', 1149, 'MG'],
  ['Zinc, Zn', 1.84, 'MG'],
  ['Copper, Cu', 0.124, 'MG'],
  ['Selenium, Se', 33.8, 'UG'],
  ['Retinol', 13, 'UG'],
  ['Vitamin A, RAE', 13, 'UG'],
  ['Carotene, beta', 0, 'UG'],
  ['Carotene, alpha', 0, 'UG'],
  ['Vitamin E (alpha-tocopherol)', 0.22, 'MG'],
  ['Vitamin D (D2 + D3)', 0.7, 'UG'],
  ['Cryptoxanthin, beta', 0, 'UG'],
  ['Lycopene', 0, 'UG'],
  ['Lutein + zeaxanthin', 0, 'UG'],
  ['Vitamin C, total ascorbic acid', 0, 'MG'],
  ['Thiamin', 0.426, 'MG'],
  ['Riboflavin', 0.191, 'MG'],
  ['Niacin', 6.055, 'MG'],
  ['Vitamin B-6', 0.411, 'MG'],
  ['Folate, total', 1, 'UG'],
  ['Vitamin B-12', 0.4, 'UG'],
  ['Choline, total', 75.6, 'MG'],
  ['Vitamin K (phylloquinone)', 0, 'UG'],
  ['Folic acid', 0, 'UG'],
  ['Folate, food', 1, 'UG'],
  ['Folate, DFE', 1, 'UG'],
  ['Vitamin E, added', 0, 'MG'],
  ['Vitamin B-12, added', 0, 'UG'],
  ['Cholesterol', 54, 'MG'],
  ['Fatty acids, total saturated', 1.285, 'G'],
  ['SFA 4:0', 0, 'G'],
  ['SFA 6:0', 0, 'G'],
  ['SFA 8:0', 0, 'G'],
  ['SFA 10:0', 0.002, 'G'],
  ['SFA 12:0', 0.002, 'G'],
  ['SFA 14:0', 0.046, 'G'],
  ['SFA 16:0', 0.797, 'G'],
  ['SFA 18:0', 0.396, 'G'],
  ['MUFA 18:1', 1.59, 'G'],
  ['PUFA 18:2', 0.436, 'G'],
  ['PUFA 18:3', 0.018, 'G'],
  ['PUFA 20:4', 0.054, 'G'],
  ['PUFA 22:6 n-3 (DHA)', 0, 'G'],
  ['MUFA 16:1', 0.105, 'G'],
  ['PUFA 18:4', 0, 'G'],
  ['MUFA 20:1', 0.025, 'G'],
  ['PUFA 20:5 n-3 (EPA)', 0, 'G'],
  ['MUFA 22:1', 0, 'G'],
  ['PUFA 22:5 n-3 (DPA)', 0.002, 'G'],
  ['Fatty acids, total monounsaturated', 1.747, 'G'],
  ['Fatty acids, total polyunsaturated', 0.549, 'G']],
 [['Protein', 0.66, 'G'],
  ['Total lipid (fat)', 2.33, 'G'],
  ['Carbohydrate, by difference', 5.37, 'G'],
  ['Energy', 45, 'KCAL'],
  ['Alcohol, ethyl', 0, 'G'],
  ['Water', 91.33, 'G'],
  ['Caffeine', 0, 'MG'],
  ['Theobromine', 0, 'MG'],
  ['Total Sugars', 2.04, 'G'],
  ['Fiber, total dietary', 0.5, 'G'],
  ['Calcium, Ca', 155, 'MG'],
  ['Iron, Fe', 0.21, 'MG'],
  ['Magnesium, Mg', 8, 'MG'],
  ['Phosphorus, P', 20, 'MG'],
  ['Potassium, K', 18, 'MG'],
  ['Sodium, Na', 43, 'MG'],
  ['Zinc, Zn', 0.19, 'MG'],
  ['Copper, Cu', 0.029, 'MG'],
  ['Selenium, Se', 1.5, 'UG'],
  ['Retinol', 0, 'UG'],
  ['Vitamin A, RAE', 0, 'UG'],
  ['Carotene, beta', 0, 'UG'],
  ['Carotene, alpha', 0, 'UG'],
  ['Vitamin E (alpha-tocopherol)', 0.37, 'MG'],
  ['Vitamin D (D2 + D3)', 1.7, 'UG'],
  ['Cryptoxanthin, beta', 0, 'UG'],
  ['Lycopene', 0, 'UG'],
  ['Lutein + zeaxanthin', 9, 'UG'],
  ['Vitamin C, total ascorbic acid', 0, 'MG'],
  ['Thiamin', 0.023, 'MG'],
  ['Riboflavin', 0.008, 'MG'],
  ['Niacin', 0.056, 'MG'],
  ['Vitamin B-6', 0.005, 'MG'],
  ['Folate, total', 2, 'UG'],
  ['Vitamin B-12', 0.5, 'UG'],
  ['Choline, total', 2, 'MG'],
  ['Vitamin K (phylloquinone)', 1.5, 'UG'],
  ['Folic acid', 0, 'UG'],
  ['Folate, food', 2, 'UG'],
  ['Folate, DFE', 2, 'UG'],
  ['Vitamin E, added', 0, 'MG'],
  ['Vitamin B-12, added', 0.5, 'UG'],
  ['Cholesterol', 0, 'MG'],
  ['Fatty acids, total saturated', 0.187, 'G'],
  ['SFA 4:0', 0, 'G'],
  ['SFA 6:0', 0, 'G'],
  ['SFA 8:0', 0, 'G'],
  ['SFA 10:0', 0, 'G'],
  ['SFA 12:0', 0.001, 'G'],
  ['SFA 14:0', 0.001, 'G'],
  ['SFA 16:0', 0.124, 'G'],
  ['SFA 18:0', 0.036, 'G'],
  ['MUFA 18:1', 1.303, 'G'],
  ['PUFA 18:2', 0.465, 'G'],
  ['PUFA 18:3', 0.154, 'G'],
  ['PUFA 20:4', 0, 'G'],
  ['PUFA 22:6 n-3 (DHA)', 0, 'G'],
  ['MUFA 16:1', 0.005, 'G'],
  ['PUFA 18:4', 0, 'G'],
  ['MUFA 20:1', 0.038, 'G'],
  ['PUFA 20:5 n-3 (EPA)', 0, 'G'],
  ['MUFA 22:1', 0, 'G'],
  ['PUFA 22:5 n-3 (DPA)', 0, 'G'],
  ['Fatty acids, total monounsaturated', 1.349, 'G'],
  ['Fatty acids, total polyunsaturated', 0.62, 'G']],
 [['Iron, Fe', 5.99, 'MG'],
  ['Magnesium, Mg', 251, 'MG'],
  ['Phosphorus, P', 532, 'MG'],
  ['Potassium, K', 638, 'MG'],
  ['Sodium, Na', 4.76, 'MG'],
  ['Zinc, Zn', 5.07, 'MG'],
  ['Nitrogen', 3.29, 'G'],
  ['Copper, Cu', 2.22, 'MG'],
  ['Total lipid (fat)', 38.9, 'G'],
  ['Manganese, Mn', 1.95, 'MG'],
  ['Ash', 2.6, 'G'],
  ['Selenium, Se', 20.7, 'UG'],
  ['Fiber, total dietary', 4.1, 'G'],
  ['Water', 4.81, 'G'],
  ['Calcium, Ca', 42.0, 'MG'],
  ['Protein', 17.4, 'G'],
  ['Carbohydrate, by difference', 36.3, 'G'],
  ['Energy (Atwater General Factors)', 565, 'KCAL'],
  ['Energy (Atwater Specific Factors)', 533, 'KCAL']],
 [['Protein', 14.11, 'G'],
  ['Total lipid (fat)', 14.11, 'G'],
  ['Carbohydrate, by difference', 62.2, 'G'],
  ['Energy', 432, 'KCAL'],
  ['Alcohol, ethyl', 0, 'G'],
  ['Water', 6.93, 'G'],
  ['Caffeine', 0, 'MG'],
  ['Theobromine', 0, 'MG'],
  ['Total Sugars', 14.11, 'G'],
  ['Fiber, total dietary', 3.8, 'G'],
  ['Calcium, Ca', 123, 'MG'],
  ['Iron, Fe', 3.8, 'MG'],
  ['Magnesium, Mg', 102, 'MG'],
  ['Phosphorus, P', 270, 'MG'],
  ['Potassium, K', 732, 'MG'],
  ['Sodium, Na', 300, 'MG'],
  ['Zinc, Zn', 3.31, 'MG'],
  ['Copper, Cu', 0.444, 'MG'],
  ['Selenium, Se', 7.2, 'UG'],
  ['Retinol', 0, 'UG'],
  ['Vitamin A, RAE', 77, 'UG'],
  ['Carotene, beta', 901, 'UG'],
  ['Carotene, alpha', 42, 'UG'],
  ['Vitamin E (alpha-tocopherol)', 2.31, 'MG'],
  ['Vitamin D (D2 + D3)', 0, 'UG'],
  ['Cryptoxanthin, beta', 0, 'UG'],
  ['Lycopene', 0, 'UG'],
  ['Lutein + zeaxanthin', 4930, 'UG'],
  ['Vitamin C, total ascorbic acid', 0, 'MG'],
  ['Thiamin', 0.614, 'MG'],
  ['Riboflavin', 0.314, 'MG'],
  ['Niacin', 5.06, 'MG'],
  ['Vitamin B-6', 0.548, 'MG'],
  ['Folate, total', 138, 'UG'],
  ['Vitamin B-12', 0, 'UG'],
  ['Choline, total', 57.9, 'MG'],
  ['Vitamin K (phylloquinone)', 50.3, 'UG'],
  ['Folic acid', 0, 'UG'],
  ['Folate, food', 138, 'UG'],
  ['Folate, DFE', 138, 'UG'],
  ['Vitamin E, added', 0, 'MG'],
  ['Vitamin B-12, added', 0, 'UG'],
  ['Cholesterol', 0, 'MG'],
  ['Fatty acids, total saturated', 5.29, 'G'],
  ['SFA 4:0', 0, 'G'],
  ['SFA 6:0', 0, 'G'],
  ['SFA 8:0', 0, 'G'],
  ['SFA 10:0', 0, 'G'],
  ['SFA 12:0', 0.01, 'G'],
  ['SFA 14:0', 0.105, 'G'],
  ['SFA 16:0', 4.672, 'G'],
  ['SFA 18:0', 0.461, 'G'],
  ['MUFA 18:1', 5.73, 'G'],
  ['PUFA 18:2', 1.82, 'G'],
  ['PUFA 18:3', 0.131, 'G'],
  ['PUFA 20:4', 0, 'G'],
  ['PUFA 22:6 n-3 (DHA)', 0, 'G'],
  ['MUFA 16:1', 0.047, 'G'],
  ['PUFA 18:4', 0, 'G'],
  ['MUFA 20:1', 0.015, 'G'],
  ['PUFA 20:5 n-3 (EPA)', 0, 'G'],
  ['MUFA 22:1', 0, 'G'],
  ['PUFA 22:5 n-3 (DPA)', 0, 'G'],
  ['Fatty acids, total monounsaturated', 5.792, 'G'],
  ['Fatty acids, total polyunsaturated', 1.951, 'G']],
 [['Protein', 0, 'G'],
  ['Total lipid (fat)', 0, 'G'],
  ['Carbohydrate, by difference', 0, 'G'],
  ['Energy', 231, 'KCAL'],
  ['Alcohol, ethyl', 33.4, 'G'],
  ['Water', 66.6, 'G'],
  ['Caffeine', 0, 'MG'],
  ['Theobromine', 0, 'MG'],
  ['Total Sugars', 0, 'G'],
  ['Fiber, total dietary', 0, 'G'],
  ['Calcium, Ca', 0, 'MG'],
  ['Iron, Fe', 0.04, 'MG'],
  ['Magnesium, Mg', 0, 'MG'],
  ['Phosphorus, P', 4, 'MG'],
  ['Potassium, K', 2, 'MG'],
  ['Sodium, Na', 1, 'MG'],
  ['Zinc, Zn', 0.04, 'MG'],
  ['Copper, Cu', 0.021, 'MG'],
  ['Selenium, Se', 0, 'UG'],
  ['Retinol', 0, 'UG'],
  ['Vitamin A, RAE', 0, 'UG'],
  ['Carotene, beta', 0, 'UG'],
  ['Carotene, alpha', 0, 'UG'],
  ['Vitamin E (alpha-tocopherol)', 0, 'MG'],
  ['Vitamin D (D2 + D3)', 0, 'UG'],
  ['Cryptoxanthin, beta', 0, 'UG'],
  ['Lycopene', 0, 'UG'],
  ['Lutein + zeaxanthin', 0, 'UG'],
  ['Vitamin C, total ascorbic acid', 0, 'MG'],
  ['Thiamin', 0.006, 'MG'],
  ['Riboflavin', 0.004, 'MG'],
  ['Niacin', 0.013, 'MG'],
  ['Vitamin B-6', 0.001, 'MG'],
  ['Folate, total', 0, 'UG'],
  ['Vitamin B-12', 0, 'UG'],
  ['Choline, total', 0, 'MG'],
  ['Vitamin K (phylloquinone)', 0, 'UG'],
  ['Folic acid', 0, 'UG'],
  ['Folate, food', 0, 'UG'],
  ['Folate, DFE', 0, 'UG'],
  ['Vitamin E, added', 0, 'MG'],
  ['Vitamin B-12, added', 0, 'UG'],
  ['Cholesterol', 0, 'MG'],
  ['Fatty acids, total saturated', 0, 'G'],
  ['SFA 4:0', 0, 'G'],
  ['SFA 6:0', 0, 'G'],
  ['SFA 8:0', 0, 'G'],
  ['SFA 10:0', 0, 'G'],
  ['SFA 12:0', 0, 'G'],
  ['SFA 14:0', 0, 'G'],
  ['SFA 16:0', 0, 'G'],
  ['SFA 18:0', 0, 'G'],
  ['MUFA 18:1', 0, 'G'],
  ['PUFA 18:2', 0, 'G'],
  ['PUFA 18:3', 0, 'G'],
  ['PUFA 20:4', 0, 'G'],
  ['PUFA 22:6 n-3 (DHA)', 0, 'G'],
  ['MUFA 16:1', 0, 'G'],
  ['PUFA 18:4', 0, 'G'],
  ['MUFA 20:1', 0, 'G'],
  ['PUFA 20:5 n-3 (EPA)', 0, 'G'],
  ['MUFA 22:1', 0, 'G'],
  ['PUFA 22:5 n-3 (DPA)', 0, 'G'],
  ['Fatty acids, total monounsaturated', 0, 'G'],
  ['Fatty acids, total polyunsaturated', 0, 'G']],
 [['Protein', 6.98, 'G'],
  ['Total lipid (fat)', 2.33, 'G'],
  ['Carbohydrate, by difference', 48.8, 'G'],
  ['Energy', 256, 'KCAL'],
  ['Total Sugars', 0.0, 'G'],
  ['Fiber, total dietary', 5.8, 'G'],
  ['Calcium, Ca', 70.0, 'MG'],
  ['Iron, Fe', 2.93, 'MG'],
  ['Sodium, Na', 651, 'MG'],
  ['Vitamin C, total ascorbic acid', 0.0, 'MG'],
  ['Cholesterol', 0.0, 'MG'],
  ['Fatty acids, total saturated', 1.16, 'G'],
  ['Vitamin A, RAE', 0.0, 'UG']],
 [['Protein', 26.5, 'G'],
  ['Total lipid (fat)', 7.35, 'G'],
  ['Carbohydrate, by difference', 53.15, 'G'],
  ['Energy', 385, 'KCAL'],
  ['Alcohol, ethyl', 0, 'G'],
  ['Water', 8.5, 'G'],
  ['Caffeine', 0, 'MG'],
  ['Theobromine', 0, 'MG'],
  ['Total Sugars', 1.8, 'G'],
  ['Fiber, total dietary', 3.5, 'G'],
  ['Calcium, Ca', 171, 'MG'],
  ['Iron, Fe', 5.2, 'MG'],
  ['Magnesium, Mg', 170, 'MG'],
  ['Phosphorus, P', 7, 'MG'],
  ['Potassium, K', 7, 'MG'],
  ['Sodium, Na', 842, 'MG'],
  ['Zinc, Zn', 1.5, 'MG'],
  ['Copper, Cu', 2.456, 'MG'],
  ['Selenium, Se', 12.1, 'UG'],
  ['Retinol', 0, 'UG'],
  ['Vitamin A, RAE', 0, 'UG'],
  ['Carotene, beta', 0, 'UG'],
  ['Carotene, alpha', 0, 'UG'],
  ['Vitamin E (alpha-tocopherol)', 1.01, 'MG'],
  ['Vitamin D (D2 + D3)', 0, 'UG'],
  ['Cryptoxanthin, beta', 0, 'UG'],
  ['Lycopene', 0, 'UG'],
  ['Lutein + zeaxanthin', 0, 'UG'],
  ['Vitamin C, total ascorbic acid', 0, 'MG'],
  ['Thiamin', 0.333, 'MG'],
  ['Riboflavin', 0.349, 'MG'],
  ['Niacin', 2.978, 'MG'],
  ['Vitamin B-6', 0.513, 'MG'],
  ['Folate, total', 240, 'UG'],
  ['Vitamin B-12', 0, 'UG'],
  ['Choline, total', 110.9, 'MG'],
  ['Vitamin K (phylloquinone)', 11.9, 'UG'],
  ['Folic acid', 0, 'UG'],
  ['Folate, food', 240, 'UG'],
  ['Folate, DFE', 240, 'UG'],
  ['Vitamin E, added', 0, 'MG'],
  ['Vitamin B-12, added', 0, 'UG'],
  ['Cholesterol', 0, 'MG'],
  ['Fatty acids, total saturated', 1.102, 'G'],
  ['SFA 4:0', 0, 'G'],
  ['SFA 6:0', 0, 'G'],
  ['SFA 8:0', 0, 'G'],
  ['SFA 10:0', 0, 'G'],
  ['SFA 12:0', 0.002, 'G'],
  ['SFA 14:0', 0.02, 'G'],
  ['SFA 16:0', 0.809, 'G'],
  ['SFA 18:0', 0.269, 'G'],
  ['MUFA 18:1', 1.628, 'G'],
  ['PUFA 18:2', 3.621, 'G'],
  ['PUFA 18:3', 0.398, 'G'],
  ['PUFA 20:4', 0, 'G'],
  ['PUFA 22:6 n-3 (DHA)', 0, 'G'],
  ['MUFA 16:1', 0.033, 'G'],
  ['PUFA 18:4', 0, 'G'],
  ['MUFA 20:1', 0, 'G'],
  ['PUFA 20:5 n-3 (EPA)', 0, 'G'],
  ['MUFA 22:1', 0, 'G'],
  ['PUFA 22:5 n-3 (DPA)', 0, 'G'],
  ['Fatty acids, total monounsaturated', 1.661, 'G'],
  ['Fatty acids, total polyunsaturated', 4.018, 'G']],
 [['Total lipid (fat)', 0.0, 'G'],
  ['Protein', 0.0, 'G'],
  ['Carbohydrate, by difference', 8.46, 'G'],
  ['Energy', 34.0, 'KCAL'],
  ['Total Sugars', 8.25, 'G'],
  ['Sodium, Na', 2.0, 'MG']],
 [['Protein', 0.0, 'G'],
  ['Total lipid (fat)', 0.0, 'G'],
  ['Carbohydrate, by difference', 0.0, 'G'],
  ['Energy', 0.0, 'KCAL'],
  ['Total Sugars', 0.0, 'G'],
  ['Sodium, Na', 0.0, 'MG'],
  ['Cholesterol', 0.0, 'MG']],
 [['Folic acid', 0.0, 'UG'],
  ['Lutein + zeaxanthin', 0.0, 'UG'],
  ['Caffeine', 0.0, 'MG'],
  ['Theobromine', 0.0, 'MG'],
  ['Total Sugars', 0.57, 'G'],
  ['Vitamin E (alpha-tocopherol)', 0.24, 'MG'],
  ['Vitamin K (phylloquinone)', 2.4, 'UG'],
  ['Cryptoxanthin, beta', 0.0, 'UG'],
  ['Lycopene', 0.0, 'UG'],
  ['Carotene, beta', 29.0, 'UG'],
  ['Carotene, alpha', 0.0, 'UG'],
  ['PUFA 22:6 n-3 (DHA)', 0.0, 'G'],
  ['PUFA 20:5 n-3 (EPA)', 0.0, 'G'],
  ['PUFA 22:5 n-3 (DPA)', 0.0, 'G'],
  ['PUFA 18:4', 0.0, 'G'],
  ['MUFA 20:1', 0.0, 'G'],
  ['MUFA 22:1', 0.0, 'G'],
  ['Vitamin A, IU', 1090.0, 'IU'],
  ['Retinol', 313, 'UG'],
  ['Vitamin A, RAE', 315, 'UG'],
  ['Energy', 1470.0, 'kJ'],
  ['Folate, food', 18.0, 'UG'],
  ['Vitamin D3 (cholecalciferol)', 0.5, 'UG'],
  ['Vitamin D (D2 + D3)', 0.5, 'UG'],
  ['Vitamin B-6', 0.053, 'MG'],
  ['Choline, total', 15.4, 'MG'],
  ['Vitamin D (D2 + D3), International Units', 21.0, 'IU'],
  ['Energy', 352, 'KCAL'],
  ['Folate, DFE', 18.0, 'UG'],
  ['Alcohol, ethyl', 0.0, 'G'],
  ['Vitamin E, added', 0.0, 'MG'],
  ['Vitamin B-12, added', 0.0, 'UG'],
  ['Niacin', 0.06, 'MG'],
  ['Pantothenic acid', 0.21, 'MG'],
  ['Water', 45.4, 'G'],
  ['Calcium, Ca', 650, 'MG'],
  ['Potassium, K', 136, 'MG'],
  ['Zinc, Zn', 2.6, 'MG'],
  ['Total lipid (fat)', 28.2, 'G'],
  ['Carbohydrate, by difference', 0.57, 'G'],
  ['SFA 4:0', 1.03, 'G'],
  ['SFA 6:0', 0.556, 'G'],
  ['SFA 10:0', 0.681, 'G'],
  ['SFA 16:0', 6.64, 'G'],
  ['SFA 18:0', 3.35, 'G'],
  ['MUFA 18:1', 8.05, 'G'],
  ['PUFA 18:2', 0.378, 'G'],
  ['PUFA 18:3', 0.351, 'G'],
  ['PUFA 20:4', 0.0, 'G'],
  ['Fatty acids, total monounsaturated', 9.34, 'G'],
  ['Fatty acids, total polyunsaturated', 0.729, 'G'],
  ['Isoleucine', 1.45, 'G'],
  ['Leucine', 2.48, 'G'],
  ['Lysine', 1.99, 'G'],
  ['Cystine', 0.134, 'G'],
  ['Valine', 1.71, 'G'],
  ['Arginine', 0.827, 'G'],
  ['Histidine', 0.686, 'G'],
  ['Aspartic acid', 1.75, 'G'],
  ['Serine', 1.36, 'G'],
  ['Protein', 23.8, 'G'],
  ['Ash', 2.0, 'G'],
  ['Fiber, total dietary', 0.0, 'G'],
  ['Iron, Fe', 0.43, 'MG'],
  ['Magnesium, Mg', 24.0, 'MG'],
  ['Phosphorus, P', 360, 'MG'],
  ['Sodium, Na', 534, 'MG'],
  ['Copper, Cu', 0.022, 'MG'],
  ['Manganese, Mn', 0.011, 'MG'],
  ['Cholesterol', 123, 'MG'],
  ['Fatty acids, total saturated', 16.7, 'G'],
  ['SFA 8:0', 0.336, 'G'],
  ['SFA 12:0', 0.768, 'G'],
  ['SFA 14:0', 2.72, 'G'],
  ['Vitamin C, total ascorbic acid', 0.0, 'MG'],
  ['Thiamin', 0.014, 'MG'],
  ['Riboflavin', 0.24, 'MG'],
  ['Folate, total', 18.0, 'UG'],
  ['Vitamin B-12', 1.5, 'UG'],
  ['Tryptophan', 0.343, 'G'],
  ['Threonine', 0.876, 'G'],
  ['Methionine', 0.734, 'G'],
  ['Phenylalanine', 1.32, 'G'],
  ['Tyrosine', 1.42, 'G'],
  ['Alanine', 0.79, 'G'],
  ['Glutamic acid', 5.35, 'G'],
  ['Glycine', 0.485, 'G'],
  ['Proline', 2.89, 'G'],
  ['MUFA 16:1', 0.833, 'G'],
  ['Selenium, Se', 14.5, 'UG']],
 [['Protein', 2.45, 'G'],
  ['Total lipid (fat)', 0.39, 'G'],
  ['Carbohydrate, by difference', 75.03, 'G'],
  ['Energy', 282, 'KCAL'],
  ['Alcohol, ethyl', 0, 'G'],
  ['Water', 20.53, 'G'],
  ['Caffeine', 0, 'MG'],
  ['Theobromine', 0, 'MG'],
  ['Total Sugars', 63.35, 'G'],
  ['Fiber, total dietary', 8, 'G'],
  ['Calcium, Ca', 39, 'MG'],
  ['Iron, Fe', 1.02, 'MG'],
  ['Magnesium, Mg', 43, 'MG'],
  ['Phosphorus, P', 62, 'MG'],
  ['Potassium, K', 656, 'MG'],
  ['Sodium, Na', 2, 'MG'],
  ['Zinc, Zn', 0.29, 'MG'],
  ['Copper, Cu', 0.206, 'MG'],
  ['Selenium, Se', 3, 'UG'],
  ['Retinol', 0, 'UG'],
  ['Vitamin A, RAE', 0, 'UG'],
  ['Carotene, beta', 6, 'UG'],
  ['Carotene, alpha', 0, 'UG'],
  ['Vitamin E (alpha-tocopherol)', 0.05, 'MG'],
  ['Vitamin D (D2 + D3)', 0, 'UG'],
  ['Cryptoxanthin, beta', 0, 'UG'],
  ['Lycopene', 0, 'UG'],
  ['Lutein + zeaxanthin', 75, 'UG'],
  ['Vitamin C, total ascorbic acid', 0.4, 'MG'],
  ['Thiamin', 0.052, 'MG'],
  ['Riboflavin', 0.066, 'MG'],
  ['Niacin', 1.274, 'MG'],
  ['Vitamin B-6', 0.165, 'MG'],
  ['Folate, total', 19, 'UG'],
  ['Vitamin B-12', 0, 'UG'],
  ['Choline, total', 6.3, 'MG'],
  ['Vitamin K (phylloquinone)', 2.7, 'UG'],
  ['Folic acid', 0, 'UG'],
  ['Folate, food', 19, 'UG'],
  ['Folate, DFE', 19, 'UG'],
  ['Vitamin E, added', 0, 'MG'],
  ['Vitamin B-12, added', 0, 'UG'],
  ['Cholesterol', 0, 'MG'],
  ['Fatty acids, total saturated', 0.032, 'G'],
  ['SFA 4:0', 0, 'G'],
  ['SFA 6:0', 0, 'G'],
  ['SFA 8:0', 0.001, 'G'],
  ['SFA 10:0', 0.001, 'G'],
  ['SFA 12:0', 0.001, 'G'],
  ['SFA 14:0', 0.001, 'G'],
  ['SFA 16:0', 0.017, 'G'],
  ['SFA 18:0', 0.011, 'G'],
  ['MUFA 18:1', 0.035, 'G'],
  ['PUFA 18:2', 0.016, 'G'],
  ['PUFA 18:3', 0.003, 'G'],
  ['PUFA 20:4', 0, 'G'],
  ['PUFA 22:6 n-3 (DHA)', 0, 'G'],
  ['MUFA 16:1', 0.001, 'G'],
  ['PUFA 18:4', 0, 'G'],
  ['MUFA 20:1', 0, 'G'],
  ['PUFA 20:5 n-3 (EPA)', 0, 'G'],
  ['MUFA 22:1', 0, 'G'],

Standardize ingredients nutrients data:

In [11]:
std_ingredients_nutrients_data: list[
    list[list[str, float]]
] = FDC.standardize_ingredients_nutrients_data(ingredients_nutrients_data, )

Check `ingredients_nutrients_data` list:

In [12]:
std_ingredients_nutrients_data

[[['protein', 12.4],
  ['fat', 2.94],
  ['carbohydrate', 5.29],
  ['sugars', 0.0],
  ['fiber', 0.6],
  ['calcium', 0.035],
  ['iron', 0.00085],
  ['sodium', 0.418],
  ['vitamin a', 3.54e-05],
  ['vitamin c', 0.0035],
  ['cholesterol', 0.032],
  ['saturated fat', 0.59]],
 [['protein', 0.0],
  ['fat', 0.0],
  ['carbohydrate', 65.0],
  ['sugars', 65.0],
  ['fiber', 0.0],
  ['calcium', 0.015],
  ['iron', 0.0],
  ['potassium', 0.105],
  ['sodium', 0.005],
  ['vitamin d', 0.0],
  ['cholesterol', 0.0],
  ['saturated fat', 0.0]],
 [['protein', 6.41],
  ['fat', 28.8],
  ['carbohydrate', 57.7],
  ['sugars', 54.5],
  ['fiber', 3.2],
  ['calcium', 0.128],
  ['iron', 0.0],
  ['sodium', 0.176],
  ['vitamin c', 0.0],
  ['cholesterol', 0.032],
  ['saturated fat', 16.0],
  ['vitamin a', 0.0]],
 [['protein', 0.0],
  ['fat', 0.0],
  ['carbohydrate', 0.0],
  ['sugars', 0.0],
  ['fiber', 0.0],
  ['calcium', 0.0],
  ['iron', 4e-05],
  ['magnesium', 0.0],
  ['phosphorus', 0.004],
  ['potassium', 0.002],
  ['sodium', 0.001],
  ['zinc', 4e-05],
  ['copper', 2.1000000000000002e-05],
  ['selenium', 0.0],
  ['vitamin a', 0.0],
  ['vitamin e', 0.0],
  ['vitamin d', 0.0],
  ['vitamin c', 0.0],
  ['thiamin', 6e-06],
  ['riboflavin', 4e-06],
  ['niacin', 1.3e-05],
  ['vitamin b 6', 1e-06],
  ['folate', 0.0],
  ['vitamin b 12', 0.0],
  ['choline', 0.0],
  ['vitamin k', 0.0],
  ['cholesterol', 0.0],
  ['saturated fat', 0.0]],
 [['protein', 19.04],
  ['fat', 3.87],
  ['carbohydrate', 1.58],
  ['sugars', 1.54],
  ['fiber', 0.0],
  ['calcium', 0.008],
  ['iron', 0.00084],
  ['magnesium', 0.02],
  ['phosphorus', 0.276],
  ['potassium', 0.371],
  ['sodium', 1.149],
  ['zinc', 0.00184],
  ['copper', 0.000124],
  ['selenium', 3.3799999999999995e-05],
  ['vitamin a', 1.3e-05],
  ['vitamin e', 0.00022],
  ['vitamin d', 7e-07],
  ['vitamin c', 0.0],
  ['thiamin', 0.000426],
  ['riboflavin', 0.000191],
  ['niacin', 0.006055],
  ['vitamin b 6', 0.00041099999999999996],
  ['folate', 1e-06],
  ['vitamin b 12', 4e-07],
  ['choline', 0.0756],
  ['vitamin k', 0.0],
  ['cholesterol', 0.054],
  ['saturated fat', 1.285]],
 [['protein', 0.66],
  ['fat', 2.33],
  ['carbohydrate', 5.37],
  ['sugars', 2.04],
  ['fiber', 0.5],
  ['calcium', 0.155],
  ['iron', 0.00021],
  ['magnesium', 0.008],
  ['phosphorus', 0.02],
  ['potassium', 0.018000000000000002],
  ['sodium', 0.043000000000000003],
  ['zinc', 0.00019],
  ['copper', 2.9000000000000004e-05],
  ['selenium', 1.5e-06],
  ['vitamin a', 0.0],
  ['vitamin e', 0.00037],
  ['vitamin d', 1.6999999999999998e-06],
  ['vitamin c', 0.0],
  ['thiamin', 2.3e-05],
  ['riboflavin', 8e-06],
  ['niacin', 5.6e-05],
  ['vitamin b 6', 5e-06],
  ['folate', 2e-06],
  ['vitamin b 12', 5e-07],
  ['choline', 0.002],
  ['vitamin k', 1.5e-06],
  ['cholesterol', 0.0],
  ['saturated fat', 0.187]],
 [['iron', 0.0059900000000000005],
  ['magnesium', 0.251],
  ['phosphorus', 0.532],
  ['potassium', 0.638],
  ['sodium', 0.0047599999999999995],
  ['zinc', 0.005070000000000001],
  ['copper', 0.00222],
  ['fat', 38.9],
  ['manganese', 0.00195],
  ['selenium', 2.07e-05],
  ['fiber', 4.1],
  ['calcium', 0.042],
  ['protein', 17.4],
  ['carbohydrate', 36.3]],
 [['protein', 14.11],
  ['fat', 14.11],
  ['carbohydrate', 62.2],
  ['sugars', 14.11],
  ['fiber', 3.8],
  ['calcium', 0.123],
  ['iron', 0.0038],
  ['magnesium', 0.10200000000000001],
  ['phosphorus', 0.27],
  ['potassium', 0.732],
  ['sodium', 0.3],
  ['zinc', 0.00331],
  ['copper', 0.000444],
  ['selenium', 7.2e-06],
  ['vitamin a', 7.7e-05],
  ['vitamin e', 0.00231],
  ['vitamin d', 0.0],
  ['vitamin c', 0.0],
  ['thiamin', 0.000614],
  ['riboflavin', 0.000314],
  ['niacin', 0.005059999999999999],
  ['vitamin b 6', 0.0005480000000000001],
  ['folate', 0.000138],
  ['vitamin b 12', 0.0],
  ['choline', 0.0579],
  ['vitamin k', 5.0299999999999996e-05],
  ['cholesterol', 0.0],
  ['saturated fat', 5.29]],
 [['protein', 0.0],
  ['fat', 0.0],
  ['carbohydrate', 0.0],
  ['sugars', 0.0],
  ['fiber', 0.0],
  ['calcium', 0.0],
  ['iron', 4e-05],
  ['magnesium', 0.0],
  ['phosphorus', 0.004],
  ['potassium', 0.002],
  ['sodium', 0.001],
  ['zinc', 4e-05],
  ['copper', 2.1000000000000002e-05],
  ['selenium', 0.0],
  ['vitamin a', 0.0],
  ['vitamin e', 0.0],
  ['vitamin d', 0.0],
  ['vitamin c', 0.0],
  ['thiamin', 6e-06],
  ['riboflavin', 4e-06],
  ['niacin', 1.3e-05],
  ['vitamin b 6', 1e-06],
  ['folate', 0.0],
  ['vitamin b 12', 0.0],
  ['choline', 0.0],
  ['vitamin k', 0.0],
  ['cholesterol', 0.0],
  ['saturated fat', 0.0]],
 [['protein', 6.98],
  ['fat', 2.33],
  ['carbohydrate', 48.8],
  ['sugars', 0.0],
  ['fiber', 5.8],
  ['calcium', 0.07],
  ['iron', 0.0029300000000000003],
  ['sodium', 0.651],
  ['vitamin c', 0.0],
  ['cholesterol', 0.0],
  ['saturated fat', 1.16],
  ['vitamin a', 0.0]],
 [['protein', 26.5],
  ['fat', 7.35],
  ['carbohydrate', 53.15],
  ['sugars', 1.8],
  ['fiber', 3.5],
  ['calcium', 0.171],
  ['iron', 0.005200000000000001],
  ['magnesium', 0.17],
  ['phosphorus', 0.007],
  ['potassium', 0.007],
  ['sodium', 0.842],
  ['zinc', 0.0015],
  ['copper', 0.002456],
  ['selenium', 1.21e-05],
  ['vitamin a', 0.0],
  ['vitamin e', 0.00101],
  ['vitamin d', 0.0],
  ['vitamin c', 0.0],
  ['thiamin', 0.000333],
  ['riboflavin', 0.00034899999999999997],
  ['niacin', 0.002978],
  ['vitamin b 6', 0.000513],
  ['folate', 0.00023999999999999998],
  ['vitamin b 12', 0.0],
  ['choline', 0.11090000000000001],
  ['vitamin k', 1.19e-05],
  ['cholesterol', 0.0],
  ['saturated fat', 1.102]],
 [['fat', 0.0],
  ['protein', 0.0],
  ['carbohydrate', 8.46],
  ['sugars', 8.25],
  ['sodium', 0.002]],
 [['protein', 0.0],
  ['fat', 0.0],
  ['carbohydrate', 0.0],
  ['sugars', 0.0],
  ['sodium', 0.0],
  ['cholesterol', 0.0]],
 [['sugars', 0.57],
  ['vitamin e', 0.00024],
  ['vitamin k', 2.4e-06],
  ['vitamin a', 0.000327],
  ['vitamin a', 0.00031499999999999996],
  ['vitamin d', 5e-07],
  ['vitamin b 6', 5.3e-05],
  ['choline', 0.0154],
  ['vitamin d', 6.3e-06],
  ['niacin', 6e-05],
  ['pantothenic acid', 0.00021],
  ['calcium', 0.65],
  ['potassium', 0.136],
  ['zinc', 0.0026000000000000003],
  ['fat', 28.2],
  ['carbohydrate', 0.57],
  ['protein', 23.8],
  ['fiber', 0.0],
  ['iron', 0.00043],
  ['magnesium', 0.024],
  ['phosphorus', 0.36],
  ['sodium', 0.534],
  ['copper', 2.2e-05],
  ['manganese', 1.1e-05],
  ['cholesterol', 0.123],
  ['saturated fat', 16.7],
  ['vitamin c', 0.0],
  ['thiamin', 1.4e-05],
  ['riboflavin', 0.00024],
  ['folate', 1.8e-05],
  ['vitamin b 12', 1.5e-06],
  ['selenium', 1.45e-05]],
 [['protein', 2.45],
  ['fat', 0.39],
  ['carbohydrate', 75.03],
  ['sugars', 63.35],
  ['fiber', 8.0],
  ['calcium', 0.039],
  ['iron', 0.00102],
  ['magnesium', 0.043000000000000003],
  ['phosphorus', 0.062],
  ['potassium', 0.656],
  ['sodium', 0.002],
  ['zinc', 0.00029],
  ['copper', 0.000206],
  ['selenium', 3e-06],
  ['vitamin a', 0.0],
  ['vitamin e', 5e-05],
  ['vitamin d', 0.0],
  ['vitamin c', 0.0004],
  ['thiamin', 5.2e-05],
  ['riboflavin', 6.6e-05],
  ['niacin', 0.001274],
  ['vitamin b 6', 0.000165],
  ['folate', 1.8999999999999998e-05],
  ['vitamin b 12', 0.0],
  ['choline', 0.0063],
  ['vitamin k', 2.7e-06],
  ['cholesterol', 0.0],
  ['saturated fat', 0.032]],
 [['protein', 20.0],
  ['fat', 5.88],
  ['carbohydrate', 0.0],
  ['sugars', 0.0],
  ['fiber', 0.0],
  ['calcium', 0.0],
  ['iron', 0.004240000000000001],
  ['sodium', 0.212],
  ['vitamin a', 0.0],
  ['vitamin c', 0.0],
  ['cholesterol', 0.053],
  ['saturated fat', 4.12]],
 [['protein', 0.8],
  ['fat', 0.08],
  ['carbohydrate', 16.28],
  ['sugars', 11.05],
  ['fiber', 0.8],
  ['calcium', 0.011],
  ['iron', 0.00041],
  ['magnesium', 0.015],
  ['phosphorus', 0.017],
  ['potassium', 0.115],
  ['sodium', 0.149],
  ['zinc', 0.00026000000000000003],
  ['copper', 0.00011600000000000001],
  ['selenium', 1e-06],
  ['vitamin a', 2e-06],
  ['vitamin e', 6e-05],
  ['vitamin d', 0.0],
  ['vitamin c', 0.0023],
  ['thiamin', 1e-05],
  ['riboflavin', 4.8e-05],
  ['niacin', 0.00025100000000000003],
  ['vitamin b 6', 5e-05],
  ['folate', 2.7e-05],
  ['vitamin b 12', 0.0],
  ['choline', 0.015],
  ['vitamin k', 3e-07],
  ['cholesterol', 0.0],
  ['saturated fat', 0.013]],
 [['protein', 0.46],
  ['fat', 0.0],
  ['carbohydrate', 3.55],
  ['sugars', 0.0],
  ['fiber', 0.0],
  ['calcium', 0.004],
  ['iron', 2e-05],
  ['magnesium', 0.006],
  ['phosphorus', 0.014],
  ['potassium', 0.027],
  ['sodium', 0.004],
  ['zinc', 1e-05],
  ['copper', 5e-06],
  ['selenium', 6e-07],
  ['vitamin a', 0.0],
  ['vitamin e', 0.0],
  ['vitamin d', 0.0],
  ['vitamin c', 0.0],
  ['thiamin', 5e-06],
  ['riboflavin', 2.5e-05],
  ['niacin', 0.000513],
  ['vitamin b 6', 4.6e-05],
  ['folate', 6e-06],
  ['vitamin b 12', 2e-08],
  ['choline', 0.0101],
  ['vitamin k', 0.0],
  ['cholesterol', 0.0],
  ['saturated fat', 0.0]],
 [['protein', 9.6],
  ['fat', 6.0],
  ['carbohydrate', 44.6],
  ['sugars', 6.25],
  ['fiber', 3.8],
  ['calcium', 0.095],
  ['iron', 0.00395],
  ['magnesium', 0.044],
  ['phosphorus', 0.122],
  ['potassium', 0.16],
  ['sodium', 0.458],
  ['zinc', 0.0010500000000000002],
  ['copper', 0.000216],
  ['selenium', 3.18e-05],
  ['vitamin a', 0.0],
  ['vitamin e', 7.000000000000001e-05],
  ['vitamin d', 0.0],
  ['vitamin c', 0.0],
  ['thiamin', 0.00046300000000000003],
  ['riboflavin', 0.00031],
  ['niacin', 0.004468],
  ['vitamin b 6', 9.2e-05],
  ['folate', 0.000111],
  ['vitamin b 12', 1e-08],
  ['choline', 0.0265],
  ['vitamin k', 3.1e-06],
  ['cholesterol', 0.0],
  ['saturated fat', 1.39]],
 [['protein', 17.9],
  ['fat', 32.1],
  ['carbohydrate', 0.0],
  ['sugars', 0.0],
  ['fiber', 0.0],
  ['calcium', 350.0],
  ['iron', 0.00357],
  ['sodium', 0.714],
  ['vitamin a', 0.0002679],
  ['cholesterol', 0.107],
  ['saturated fat', 21.4]],
 [['protein', 15.93],
  ['fat', 13.69],
  ['carbohydrate', 11.72],
  ['sugars', 0.2],
  ['fiber', 0.5],
  ['calcium', 0.022],
  ['iron', 0.0011200000000000001],
  ['magnesium', 0.036000000000000004],
  ['phosphorus', 0.17],
  ['potassium', 0.219],
  ['sodium', 0.395],
  ['zinc', 0.00045000000000000004],
  ['copper', 4.2000000000000004e-05],
  ['selenium', 3.09e-05],
  ['vitamin a', 3.2e-05],
  ['vitamin e', 0.0028799999999999997],
  ['vitamin d', 4.2999999999999995e-06],
  ['vitamin c', 0.0],
  ['thiamin', 0.000216],
  ['riboflavin', 0.00016],
  ['niacin', 0.0022429999999999998],
  ['vitamin b 6', 0.00028599999999999996],
  ['folate', 2.8e-05],
  ['vitamin b 12', 2.3e-07],
  ['choline', 0.0531],
  ['vitamin k', 1.2e-05],
  ['cholesterol', 0.037],
  ['saturated fat', 2.051]],
 [['protein', 17.88],
  ['fat', 0.74],
  ['carbohydrate', 0.0],
  ['sugars', 0.0],
  ['fiber', 0.0],
  ['calcium', 0.091],
  ['iron', 0.0005],
  ['magnesium', 0.036000000000000004],
  ['phosphorus', 0.234],
  ['potassium', 0.259],
  ['sodium', 0.395],
  ['zinc', 0.00381],
  ['copper', 0.0008139999999999999],
  ['selenium', 4.29e-05],
  ['vitamin a', 1e-06],
  ['vitamin e', 0.00184],
  ['vitamin d', 0.0],
  ['vitamin c', 0.0033],
  ['thiamin', 2.3e-05],
  ['riboflavin', 9.3e-05],
  ['niacin', 0.002747],
  ['vitamin b 6', 0.000156],
  ['folate', 5.1e-05],
  ['vitamin b 12', 3.33e-06],
  ['choline', 0.08090000000000001],
  ['vitamin k', 3e-07],
  ['cholesterol', 0.097],
  ['saturated fat', 0.201]],
 [['protein', 5.44],
  ['fat', 3.7],
  ['carbohydrate', 15.89],
  ['sugars', 0.99],
  ['fiber', 4.9],
  ['calcium', 0.026000000000000002],
  ['iron', 0.0016],
  ['magnesium', 0.04],
  ['phosphorus', 0.105],
  ['potassium', 0.368],
  ['sodium', 0.443],
  ['zinc', 0.00069],
  ['copper', 0.00019600000000000002],
  ['selenium', 7.699999999999999e-06],
  ['vitamin a', 0.0],
  ['vitamin e', 0.00091],
  ['vitamin d', 0.0],
  ['vitamin c', 0.0006],
  ['thiamin', 8.999999999999999e-05],
  ['riboflavin', 0.0001],
  ['niacin', 0.00043],
  ['vitamin b 6', 0.000115],
  ['folate', 2.1e-05],
  ['vitamin b 12', 0.0],
  ['choline', 0.016300000000000002],
  ['vitamin k', 1.6999999999999998e-06],
  ['cholesterol', 0.0],
  ['saturated fat', 0.529]],
 [['protein', 11.8],
  ['fat', 7.9],
  ['carbohydrate', 10.3],
  ['sugars', 1.8],
  ['fiber', 1.0],
  ['calcium', 0.043000000000000003],
  ['iron', 0.00124],
  ['magnesium', 0.02],
  ['phosphorus', 0.155],
  ['potassium', 0.185],
  ['sodium', 0.454],
  ['zinc', 0.0007800000000000001],
  ['copper', 7.2e-05],
  ['selenium', 2.11e-05],
  ['vitamin a', 6.599999999999999e-05],
  ['vitamin e', 0.00071],
  ['vitamin d', 2e-07],
  ['vitamin c', 0.0159],
  ['thiamin', 0.000157],
  ['riboflavin', 0.000105],
  ['niacin', 0.002198],
  ['vitamin b 6', 0.000146],
  ['folate', 1.8999999999999998e-05],
  ['vitamin b 12', 4.0399999999999994e-06],
  ['choline', 0.0422],
  ['vitamin k', 8.3e-06],
  ['cholesterol', 0.025],
  ['saturated fat', 2.22]],
 [['protein', 0.0],
  ['fat', 28.6],
  ['carbohydrate', 10.7],
  ['sodium', 0.679],
  ['vitamin b 12', 2.4999999999999998e-06],
  ['saturated fat', 25.0]],
 [['protein', 0.36],
  ['fat', 0.13],
  ['carbohydrate', 60.66],
  ['sugars', 30.54],
  ['fiber', 0.6],
  ['calcium', 0.011],
  ['iron', 0.00039000000000000005],
  ['magnesium', 0.005],
  ['phosphorus', 0.009000000000000001],
  ['potassium', 0.08700000000000001],
  ['sodium', 0.712],
  ['zinc', 0.00021],
  ['copper', 3.7e-05],
  ['selenium', 1.3e-06],
  ['vitamin a', 8e-06],
  ['vitamin e', 0.0002],
  ['vitamin d', 0.0],
  ['vitamin c', 0.0009000000000000001],
  ['thiamin', 2.3e-05],
  ['riboflavin', 1.4e-05],
  ['niacin', 0.00023899999999999998],
  ['vitamin b 6', 3.2e-05],
  ['folate', 2e-06],
  ['vitamin b 12', 0.0],
  ['choline', 0.0017],
  ['vitamin k', 3e-07],
  ['cholesterol', 0.0],
  ['saturated fat', 0.051]],
 [['protein', 0.8],
  ['fat', 0.0],
  ['carbohydrate', 12.8],
  ['sugars', 6.4],
  ['fiber', 0.8],
  ['calcium', 0.003],
  ['iron', 0.0],
  ['potassium', 0.068],
  ['sodium', 0.24],
  ['vitamin d', 0.0],
  ['cholesterol', 0.0],
  ['saturated fat', 0.0]],
 [['vitamin e', 0.00012],
  ['folate', 8e-06],
  ['sodium', 0.808],
  ['vitamin a', 4e-06],
  ['calcium', 0.054],
  ['potassium', 0.112],
  ['zinc', 0.00011],
  ['niacin', 0.000109],
  ['pantothenic acid', 0.0002],
  ['vitamin b 6', 3.4000000000000007e-05],
  ['fat', 0.43],
  ['carbohydrate', 1.99],
  ['protein', 0.48],
  ['fiber', 1.0],
  ['iron', 0.00023],
  ['magnesium', 0.0070999999999999995],
  ['phosphorus', 0.016],
  ['vitamin c', 0.0021000000000000003],
  ['copper', 2.6e-05],
  ['manganese', 5.6e-05],
  ['vitamin k', 1.68e-05],
  ['thiamin', 4.7000000000000004e-05],
  ['riboflavin', 5.7e-05]],
 [['protein', 1.35],
  ['fat', 0.68],
  ['carbohydrate', 14.9],
  ['sugars', 8.78],
  ['fiber', 2.7],
  ['calcium', 0.041],
  ['iron', 0.00024],
  ['potassium', 0.311],
  ['sodium', 0.0],
  ['vitamin a', 2.0399999999999998e-05],
  ['vitamin c', 0.0932],
  ['vitamin k', 3.78e-05],
  ['cholesterol', 0.0],
  ['saturated fat', 0.0]],
 [['protein', 1.57],
  ['fat', 3.05],
  ['carbohydrate', 14.74],
  ['sugars', 4.07],
  ['fiber', 1.9],
  ['calcium', 0.062],
  ['iron', 0.00219],
  ['magnesium', 0.029],
  ['phosphorus', 0.037],
  ['potassium', 0.188],
  ['sodium', 0.151],
  ['zinc', 0.00013000000000000002],
  ['copper', 0.000125],
  ['selenium', 1e-06],
  ['vitamin a', 9.4e-05],
  ['vitamin e', 0.0013700000000000001],
  ['vitamin d', 0.0],
  ['vitamin c', 0.0106],
  ['thiamin', 5.6e-05],
  ['riboflavin', 3e-05],
  ['niacin', 0.00039600000000000003],
  ['vitamin b 6', 0.000236],
  ['folate', 5.6999999999999996e-05],
  ['vitamin b 12', 0.0],
  ['choline', 0.0101],
  ['vitamin k', 5.12e-05],
  ['cholesterol', 0.002],
  ['saturated fat', 0.758]],
 [['protein', 8.82],
  ['fat', 15.02],
  ['carbohydrate', 39.83],
  ['sugars', 37.32],
  ['fiber', 0.8],
  ['calcium', 0.039],
  ['iron', 0.00134],
  ['magnesium', 0.02],
  ['phosphorus', 0.145],
  ['potassium', 0.14300000000000002],
  ['sodium', 0.079],
  ['zinc', 0.00125],
  ['copper', 0.00011600000000000001],
  ['selenium', 1.9600000000000002e-05],
  ['vitamin a', 0.00010999999999999999],
  ['vitamin e', 0.00084],
  ['vitamin d', 1.5e-06],
  ['vitamin c', 0.005],
  ['thiamin', 9.7e-05],
  ['riboflavin', 0.00026700000000000004],
  ['niacin', 0.000131],
  ['vitamin b 6', 6.2e-05],
  ['folate', 3.6e-05],
  ['vitamin b 12', 5e-07],
  ['choline', 0.1688],
  ['vitamin k', 8e-07],
  ['cholesterol', 0.25],
  ['saturated fat', 2.727]],
 [['protein', 3.54],
  ['fat', 0.88],
  ['carbohydrate', 9.73],
  ['sugars', 0.0],
  ['fiber', 1.8],
  ['calcium', 0.133],
  ['iron', 0.00159],
  ['magnesium', 0.035],
  ['phosphorus', 0.053],
  ['potassium', 0.447],
  ['sodium', 0.044],
  ['copper', 0.00026500000000000004],
  ['manganese', 0.001],
  ['vitamin a', 0.00465],
  ['vitamin c', 0.122],
  ['thiamin', 0.0],
  ['riboflavin', 0.00012],
  ['niacin', 0.0010600000000000002],
  ['vitamin b 6', 0.00026500000000000004],
  ['folate', 2.8e-05],
  ['vitamin k', 0.000828],
  ['cholesterol', 0.0],
  ['saturated fat', 0.0]],
 [['protein', 0.0],
  ['fat', 0.0],
  ['carbohydrate', 105.0],
  ['sugars', 105.0],
  ['sodium', 0.0]],
 [['protein', 0.37],
  ['fat', 0.15],
  ['carbohydrate', 15.18],
  ['sugars', 9.73],
  ['fiber', 3.1],
  ['calcium', 0.009000000000000001],
  ['iron', 0.00017999999999999998],
  ['magnesium', 0.007],
  ['phosphorus', 0.011],
  ['potassium', 0.10400000000000001],
  ['sodium', 0.003],
  ['zinc', 8.999999999999999e-05],
  ['copper', 7.7e-05],
  ['selenium', 1e-07],
  ['vitamin a', 1e-06],
  ['vitamin e', 0.00012],
  ['vitamin d', 0.0],
  ['vitamin c', 0.0043],
  ['thiamin', 1.2e-05],
  ['riboflavin', 2.6e-05],
  ['niacin', 0.000162],
  ['vitamin b 6', 2.8e-05],
  ['folate', 7e-06],
  ['vitamin b 12', 0.0],
  ['choline', 0.0050999999999999995],
  ['vitamin k', 4.2e-06],
  ['cholesterol', 0.0],
  ['saturated fat', 0.022]],
 [['calcium', 0.0],
  ['iron', 0.00321],
  ['sodium', 0.0],
  ['vitamin a', 0.0],
  ['vitamin c', 0.0],
  ['thiamin', 0.001],
  ['riboflavin', 0.000304],
  ['niacin', 0.00536],
  ['cholesterol', 0.0],
  ['saturated fat', 0.0],
  ['protein', 12.5],
  ['fat', 1.79],
  ['carbohydrate', 78.6],
  ['sugars', 3.57],
  ['fiber', 3.6]],
 [['protein', 0.7],
  ['fat', 0.28],
  ['carbohydrate', 11.42],
  ['sugars', 9.92],
  ['fiber', 1.4],
  ['calcium', 0.006],
  ['iron', 0.00017],
  ['magnesium', 0.007],
  ['phosphorus', 0.016],
  ['potassium', 0.157],
  ['sodium', 0.0],
  ['zinc', 0.0001],
  ['copper', 5.7e-05],
  ['selenium', 0.0],
  ['vitamin a', 1.7e-05],
  ['vitamin e', 0.00026000000000000003],
  ['vitamin d', 0.0],
  ['vitamin c', 0.0095],
  ['thiamin', 2.8e-05],
  ['riboflavin', 2.6e-05],
  ['niacin', 0.000417],
  ['vitamin b 6', 2.9000000000000004e-05],
  ['folate', 4.9999999999999996e-06],
  ['vitamin b 12', 0.0],
  ['choline', 0.0019],
  ['vitamin k', 6.4e-06],
  ['cholesterol', 0.0],
  ['saturated fat', 0.017]],
 [['fat', 0.0],
  ['calcium', 0.08],
  ['iron', 0.00054],
  ['vitamin a', 0.00010499999999999999],
  ['vitamin c', 0.012],
  ['cholesterol', 0.0],
  ['saturated fat', 0.0],
  ['protein', 3.0],
  ['carbohydrate', 8.0],
  ['sugars', 0.0],
  ['fiber', 1.0],
  ['sodium', 0.003]],
 [['protein', 21.2],
  ['fat', 4.12],
  ['carbohydrate', 1.18],
  ['sugars', 0.0],
  ['fiber', 0.0],
  ['calcium', 0.0],
  ['iron', 0.00127],
  ['sodium', 0.212],
  ['vitamin a', 0.0],
  ['vitamin c', 0.0],
  ['cholesterol', 0.076],
  ['saturated fat', 2.35]],
 [['fiber', 4.8],
  ['vitamin d', 0.0],
  ['vitamin d', 0.0],
  ['vitamin a', 1.2e-05],
  ['vitamin c', 0.0060999999999999995],
  ['thiamin', 0.00029],
  ['riboflavin', 0.00017],
  ['folate', 4.9e-05],
  ['vitamin b 12', 0.0],
  ['cholesterol', 0.0],
  ['saturated fat', 0.621],
  ['iron', 0.0006],
  ['magnesium', 0.05],
  ['phosphorus', 0.124],
  ['sodium', 0.023],
  ['copper', 0.00107],
  ['manganese', 0.000132],
  ['vitamin a', 7.14e-05],
  ['protein', 5.3],
  ['calcium', 0.061],
  ['potassium', 0.875],
  ['zinc', 0.00083],
  ['niacin', 0.0053],
  ['pantothenic acid', 0.000816],
  ['vitamin b 6', 0.000298],
  ['fat', 2.3],
  ['carbohydrate', 32.0]],
 [['sugars', 0.0],
  ['vitamin e', 0.0],
  ['vitamin a', 0.0],
  ['vitamin d', 0.0],

Simplify ingredients nutrients data:

In [13]:
std_ingredients_nutrients_data: list[
    dict[str, float]
] = FDC.get_standardized_ingredients_nutrients_data(
    "food.json",
    "../data/json/",
    std_ingredients_nutrients_data,
)

Check `ingredients_nutrients_data` list:

In [14]:
std_ingredients_nutrients_data

[{'fat': 2.94,
  'iron': 0.00085,
  'zinc': 0,
  'fiber': 0.6,
  'sugars': 0.0,
  'sodium': 0.418,
  'niacin': 0,
  'folate': 0,
  'copper': 0,
  'biotin': 0,
  'iodine': 0,
  'protein': 12.4,
  'calcium': 0.035,
  'choline': 0,
  'thiamin': 0,
  'chloride': 0,
  'selenium': 0,
  'chromium': 0,
  'potassium': 0,
  'vitamin c': 0.0035,
  'magnesium': 0,
  'vitamin e': 0,
  'vitamin a': 3.54e-05,
  'manganese': 0,
  'vitamin d': 0,
  'vitamin k': 0,
  'phosphorus': 0,
  'riboflavin': 0,
  'vitamin b 6': 0,
  'molybdenum': 0,
  'cholesterol': 0.032,
  'vitamin b 12': 0,
  'carbohydrate': 5.29,
  'saturated fat': 0.59,
  'pantothenic acid': 0},
 {'fat': 0.0,
  'iron': 0.0,
  'zinc': 0,
  'fiber': 0.0,
  'sugars': 65.0,
  'sodium': 0.005,
  'niacin': 0,
  'folate': 0,
  'copper': 0,
  'biotin': 0,
  'iodine': 0,
  'protein': 0.0,
  'calcium': 0.015,
  'choline': 0,
  'thiamin': 0,
  'chloride': 0,
  'selenium': 0,
  'chromium': 0,
  'potassium': 0.105,
  'vitamin c': 0,
  'magnesium': 0,
  'vitamin e': 0,
  'vitamin a': 0,
  'manganese': 0,
  'vitamin d': 0.0,
  'vitamin k': 0,
  'phosphorus': 0,
  'riboflavin': 0,
  'vitamin b 6': 0,
  'molybdenum': 0,
  'cholesterol': 0.0,
  'vitamin b 12': 0,
  'carbohydrate': 65.0,
  'saturated fat': 0.0,
  'pantothenic acid': 0},
 {'fat': 28.8,
  'iron': 0.0,
  'zinc': 0,
  'fiber': 3.2,
  'sugars': 54.5,
  'sodium': 0.176,
  'niacin': 0,
  'folate': 0,
  'copper': 0,
  'biotin': 0,
  'iodine': 0,
  'protein': 6.41,
  'calcium': 0.128,
  'choline': 0,
  'thiamin': 0,
  'chloride': 0,
  'selenium': 0,
  'chromium': 0,
  'potassium': 0,
  'vitamin c': 0.0,
  'magnesium': 0,
  'vitamin e': 0,
  'vitamin a': 0.0,
  'manganese': 0,
  'vitamin d': 0,
  'vitamin k': 0,
  'phosphorus': 0,
  'riboflavin': 0,
  'vitamin b 6': 0,
  'molybdenum': 0,
  'cholesterol': 0.032,
  'vitamin b 12': 0,
  'carbohydrate': 57.7,
  'saturated fat': 16.0,
  'pantothenic acid': 0},
 {'fat': 0.0,
  'iron': 4e-05,
  'zinc': 4e-05,
  'fiber': 0.0,
  'sugars': 0.0,
  'sodium': 0.001,
  'niacin': 1.3e-05,
  'folate': 0.0,
  'copper': 2.1000000000000002e-05,
  'biotin': 0,
  'iodine': 0,
  'protein': 0.0,
  'calcium': 0.0,
  'choline': 0.0,
  'thiamin': 6e-06,
  'chloride': 0,
  'selenium': 0.0,
  'chromium': 0,
  'potassium': 0.002,
  'vitamin c': 0.0,
  'magnesium': 0.0,
  'vitamin e': 0.0,
  'vitamin a': 0.0,
  'manganese': 0,
  'vitamin d': 0.0,
  'vitamin k': 0.0,
  'phosphorus': 0.004,
  'riboflavin': 4e-06,
  'vitamin b 6': 1e-06,
  'molybdenum': 0,
  'cholesterol': 0.0,
  'vitamin b 12': 0.0,
  'carbohydrate': 0.0,
  'saturated fat': 0.0,
  'pantothenic acid': 0},
 {'fat': 3.87,
  'iron': 0.00084,
  'zinc': 0.00184,
  'fiber': 0.0,
  'sugars': 1.54,
  'sodium': 1.149,
  'niacin': 0.006055,
  'folate': 1e-06,
  'copper': 0.000124,
  'biotin': 0,
  'iodine': 0,
  'protein': 19.04,
  'calcium': 0.008,
  'choline': 0.0756,
  'thiamin': 0.000426,
  'chloride': 0,
  'selenium': 3.3799999999999995e-05,
  'chromium': 0,
  'potassium': 0.371,
  'vitamin c': 0.0,
  'magnesium': 0.02,
  'vitamin e': 0.00022,
  'vitamin a': 1.3e-05,
  'manganese': 0,
  'vitamin d': 7e-07,
  'vitamin k': 0.0,
  'phosphorus': 0.276,
  'riboflavin': 0.000191,
  'vitamin b 6': 0.00041099999999999996,
  'molybdenum': 0,
  'cholesterol': 0.054,
  'vitamin b 12': 4e-07,
  'carbohydrate': 1.58,
  'saturated fat': 1.285,
  'pantothenic acid': 0},
 {'fat': 2.33,
  'iron': 0.00021,
  'zinc': 0.00019,
  'fiber': 0.5,
  'sugars': 2.04,
  'sodium': 0.043000000000000003,
  'niacin': 5.6e-05,
  'folate': 2e-06,
  'copper': 2.9000000000000004e-05,
  'biotin': 0,
  'iodine': 0,
  'protein': 0.66,
  'calcium': 0.155,
  'choline': 0.002,
  'thiamin': 2.3e-05,
  'chloride': 0,
  'selenium': 1.5e-06,
  'chromium': 0,
  'potassium': 0.018000000000000002,
  'vitamin c': 0.0,
  'magnesium': 0.008,
  'vitamin e': 0.00037,
  'vitamin a': 0.0,
  'manganese': 0,
  'vitamin d': 1.6999999999999998e-06,
  'vitamin k': 1.5e-06,
  'phosphorus': 0.02,
  'riboflavin': 8e-06,
  'vitamin b 6': 5e-06,
  'molybdenum': 0,
  'cholesterol': 0.0,
  'vitamin b 12': 5e-07,
  'carbohydrate': 5.37,
  'saturated fat': 0.187,
  'pantothenic acid': 0},
 {'fat': 38.9,
  'iron': 0.0059900000000000005,
  'zinc': 0.005070000000000001,
  'fiber': 4.1,
  'sugars': 0,
  'sodium': 0.0047599999999999995,
  'niacin': 0,
  'folate': 0,
  'copper': 0.00222,
  'biotin': 0,
  'iodine': 0,
  'protein': 17.4,
  'calcium': 0.042,
  'choline': 0,
  'thiamin': 0,
  'chloride': 0,
  'selenium': 2.07e-05,
  'chromium': 0,
  'potassium': 0.638,
  'vitamin c': 0,
  'magnesium': 0.251,
  'vitamin e': 0,
  'vitamin a': 0,
  'manganese': 0.00195,
  'vitamin d': 0,
  'vitamin k': 0,
  'phosphorus': 0.532,
  'riboflavin': 0,
  'vitamin b 6': 0,
  'molybdenum': 0,
  'cholesterol': 0,
  'vitamin b 12': 0,
  'carbohydrate': 36.3,
  'saturated fat': 0,
  'pantothenic acid': 0},
 {'fat': 14.11,
  'iron': 0.0038,
  'zinc': 0.00331,
  'fiber': 3.8,
  'sugars': 14.11,
  'sodium': 0.3,
  'niacin': 0.005059999999999999,
  'folate': 0.000138,
  'copper': 0.000444,
  'biotin': 0,
  'iodine': 0,
  'protein': 14.11,
  'calcium': 0.123,
  'choline': 0.0579,
  'thiamin': 0.000614,
  'chloride': 0,
  'selenium': 7.2e-06,
  'chromium': 0,
  'potassium': 0.732,
  'vitamin c': 0.0,
  'magnesium': 0.10200000000000001,
  'vitamin e': 0.00231,
  'vitamin a': 7.7e-05,
  'manganese': 0,
  'vitamin d': 0.0,
  'vitamin k': 5.0299999999999996e-05,
  'phosphorus': 0.27,
  'riboflavin': 0.000314,
  'vitamin b 6': 0.0005480000000000001,
  'molybdenum': 0,
  'cholesterol': 0.0,
  'vitamin b 12': 0.0,
  'carbohydrate': 62.2,
  'saturated fat': 5.29,
  'pantothenic acid': 0},
 {'fat': 0.0,
  'iron': 4e-05,
  'zinc': 4e-05,
  'fiber': 0.0,
  'sugars': 0.0,
  'sodium': 0.001,
  'niacin': 1.3e-05,
  'folate': 0.0,
  'copper': 2.1000000000000002e-05,
  'biotin': 0,
  'iodine': 0,
  'protein': 0.0,
  'calcium': 0.0,
  'choline': 0.0,
  'thiamin': 6e-06,
  'chloride': 0,
  'selenium': 0.0,
  'chromium': 0,
  'potassium': 0.002,
  'vitamin c': 0.0,
  'magnesium': 0.0,
  'vitamin e': 0.0,
  'vitamin a': 0.0,
  'manganese': 0,
  'vitamin d': 0.0,
  'vitamin k': 0.0,
  'phosphorus': 0.004,
  'riboflavin': 4e-06,
  'vitamin b 6': 1e-06,
  'molybdenum': 0,
  'cholesterol': 0.0,
  'vitamin b 12': 0.0,
  'carbohydrate': 0.0,
  'saturated fat': 0.0,
  'pantothenic acid': 0},
 {'fat': 2.33,
  'iron': 0.0029300000000000003,
  'zinc': 0,
  'fiber': 5.8,
  'sugars': 0.0,
  'sodium': 0.651,
  'niacin': 0,
  'folate': 0,
  'copper': 0,
  'biotin': 0,
  'iodine': 0,
  'protein': 6.98,
  'calcium': 0.07,
  'choline': 0,
  'thiamin': 0,
  'chloride': 0,
  'selenium': 0,
  'chromium': 0,
  'potassium': 0,
  'vitamin c': 0.0,
  'magnesium': 0,
  'vitamin e': 0,
  'vitamin a': 0.0,
  'manganese': 0,
  'vitamin d': 0,
  'vitamin k': 0,
  'phosphorus': 0,
  'riboflavin': 0,
  'vitamin b 6': 0,
  'molybdenum': 0,
  'cholesterol': 0.0,
  'vitamin b 12': 0,
  'carbohydrate': 48.8,
  'saturated fat': 1.16,
  'pantothenic acid': 0},
 {'fat': 7.35,
  'iron': 0.005200000000000001,
  'zinc': 0.0015,
  'fiber': 3.5,
  'sugars': 1.8,
  'sodium': 0.842,
  'niacin': 0.002978,
  'folate': 0.00023999999999999998,
  'copper': 0.002456,
  'biotin': 0,
  'iodine': 0,
  'protein': 26.5,
  'calcium': 0.171,
  'choline': 0.11090000000000001,
  'thiamin': 0.000333,
  'chloride': 0,
  'selenium': 1.21e-05,
  'chromium': 0,
  'potassium': 0.007,
  'vitamin c': 0.0,
  'magnesium': 0.17,
  'vitamin e': 0.00101,
  'vitamin a': 0.0,
  'manganese': 0,
  'vitamin d': 0.0,
  'vitamin k': 1.19e-05,
  'phosphorus': 0.007,
  'riboflavin': 0.00034899999999999997,
  'vitamin b 6': 0.000513,
  'molybdenum': 0,
  'cholesterol': 0.0,
  'vitamin b 12': 0.0,
  'carbohydrate': 53.15,
  'saturated fat': 1.102,
  'pantothenic acid': 0},
 {'fat': 0.0,
  'iron': 0,
  'zinc': 0,
  'fiber': 0,
  'sugars': 8.25,
  'sodium': 0.002,
  'niacin': 0,
  'folate': 0,
  'copper': 0,
  'biotin': 0,
  'iodine': 0,
  'protein': 0.0,
  'calcium': 0,
  'choline': 0,
  'thiamin': 0,
  'chloride': 0,
  'selenium': 0,
  'chromium': 0,
  'potassium': 0,
  'vitamin c': 0,
  'magnesium': 0,
  'vitamin e': 0,
  'vitamin a': 0,
  'manganese': 0,
  'vitamin d': 0,
  'vitamin k': 0,
  'phosphorus': 0,
  'riboflavin': 0,
  'vitamin b 6': 0,
  'molybdenum': 0,
  'cholesterol': 0,
  'vitamin b 12': 0,
  'carbohydrate': 8.46,
  'saturated fat': 0,
  'pantothenic acid': 0},
 {'fat': 0.0,
  'iron': 0,
  'zinc': 0,
  'fiber': 0,
  'sugars': 0.0,
  'sodium': 0.0,
  'niacin': 0,
  'folate': 0,
  'copper': 0,
  'biotin': 0,
  'iodine': 0,
  'protein': 0.0,
  'calcium': 0,
  'choline': 0,
  'thiamin': 0,
  'chloride': 0,
  'selenium': 0,
  'chromium': 0,
  'potassium': 0,
  'vitamin c': 0,
  'magnesium': 0,
  'vitamin e': 0,
  'vitamin a': 0,
  'manganese': 0,
  'vitamin d': 0,
  'vitamin k': 0,
  'phosphorus': 0,
  'riboflavin': 0,
  'vitamin b 6': 0,
  'molybdenum': 0,
  'cholesterol': 0.0,
  'vitamin b 12': 0,
  'carbohydrate': 0.0,
  'saturated fat': 0,
  'pantothenic acid': 0},
 {'fat': 28.2,
  'iron': 0.00043,
  'zinc': 0.0026000000000000003,
  'fiber': 0.0,
  'sugars': 0.57,
  'sodium': 0.534,
  'niacin': 6e-05,
  'folate': 1.8e-05,
  'copper': 2.2e-05,
  'biotin': 0,
  'iodine': 0,
  'protein': 23.8,
  'calcium': 0.65,
  'choline': 0.0154,
  'thiamin': 1.4e-05,
  'chloride': 0,
  'selenium': 1.45e-05,
  'chromium': 0,
  'potassium': 0.136,
  'vitamin c': 0.0,
  'magnesium': 0.024,
  'vitamin e': 0.00024,
  'vitamin a': 0.00031499999999999996,
  'manganese': 1.1e-05,
  'vitamin d': 6.3e-06,
  'vitamin k': 2.4e-06,
  'phosphorus': 0.36,
  'riboflavin': 0.00024,
  'vitamin b 6': 5.3e-05,
  'molybdenum': 0,
  'cholesterol': 0.123,
  'vitamin b 12': 1.5e-06,
  'carbohydrate': 0.57,
  'saturated fat': 16.7,
  'pantothenic acid': 0.00021},
 {'fat': 0.39,
  'iron': 0.00102,
  'zinc': 0.00029,
  'fiber': 8.0,
  'sugars': 63.35,
  'sodium': 0.002,
  'niacin': 0.001274,
  'folate': 1.8999999999999998e-05,
  'copper': 0.000206,
  'biotin': 0,
  'iodine': 0,
  'protein': 2.45,
  'calcium': 0.039,
  'choline': 0.0063,
  'thiamin': 5.2e-05,
  'chloride': 0,
  'selenium': 3e-06,
  'chromium': 0,
  'potassium': 0.656,
  'vitamin c': 0.0004,
  'magnesium': 0.043000000000000003,
  'vitamin e': 5e-05,
  'vitamin a': 0.0,
  'manganese': 0,
  'vitamin d': 0.0,
  'vitamin k': 2.7e-06,
  'phosphorus': 0.062,
  'riboflavin': 6.6e-05,
  'vitamin b 6': 0.000165,
  'molybdenum': 0,
  'cholesterol': 0.0,
  'vitamin b 12': 0.0,
  'carbohydrate': 75.03,
  'saturated fat': 0.032,
  'pantothenic acid': 0},
 {'fat': 5.88,
  'iron': 0.004240000000000001,
  'zinc': 0,
  'fiber': 0.0,
  'sugars': 0.0,
  'sodium': 0.212,
  'niacin': 0,
  'folate': 0,
  'copper': 0,
  'biotin': 0,
  'iodine': 0,
  'protein': 20.0,
  'calcium': 0.0,
  'choline': 0,
  'thiamin': 0,
  'chloride': 0,
  'selenium': 0,
  'chromium': 0,
  'potassium': 0,
  'vitamin c': 0.0,
  'magnesium': 0,
  'vitamin e': 0,
  'vitamin a': 0.0,
  'manganese': 0,
  'vitamin d': 0,
  'vitamin k': 0,
  'phosphorus': 0,
  'riboflavin': 0,
  'vitamin b 6': 0,
  'molybdenum': 0,
  'cholesterol': 0.053,
  'vitamin b 12': 0,
  'carbohydrate': 0.0,
  'saturated fat': 4.12,
  'pantothenic acid': 0},
 {'fat': 0.08,
  'iron': 0.00041,
  'zinc': 0.00026000000000000003,
  'fiber': 0.8,
  'sugars': 11.05,
  'sodium': 0.149,
  'niacin': 0.00025100000000000003,
  'folate': 2.7e-05,
  'copper': 0.00011600000000000001,
  'biotin': 0,
  'iodine': 0,
  'protein': 0.8,
  'calcium': 0.011,
  'choline': 0.015,
  'thiamin': 1e-05,
  'chloride': 0,
  'selenium': 1e-06,
  'chromium': 0,
  'potassium': 0.115,
  'vitamin c': 0.0023,
  'magnesium': 0.015,
  'vitamin e': 6e-05,
  'vitamin a': 2e-06,
  'manganese': 0,
  'vitamin d': 0.0,
  'vitamin k': 3e-07,
  'phosphorus': 0.017,
  'riboflavin': 4.8e-05,
  'vitamin b 6': 5e-05,
  'molybdenum': 0,
  'cholesterol': 0.0,
  'vitamin b 12': 0.0,
  'carbohydrate': 16.28,
  'saturated fat': 0.013,
  'pantothenic acid': 0},
 {'fat': 0.0,
  'iron': 2e-05,
  'zinc': 1e-05,
  'fiber': 0.0,
  'sugars': 0.0,
  'sodium': 0.004,
  'niacin': 0.000513,
  'folate': 6e-06,
  'copper': 5e-06,
  'biotin': 0,
  'iodine': 0,
  'protein': 0.46,
  'calcium': 0.004,
  'choline': 0.0101,
  'thiamin': 5e-06,
  'chloride': 0,
  'selenium': 6e-07,
  'chromium': 0,
  'potassium': 0.027,
  'vitamin c': 0.0,
  'magnesium': 0.006,
  'vitamin e': 0.0,
  'vitamin a': 0.0,
  'manganese': 0,
  'vitamin d': 0.0,
  'vitamin k': 0.0,
  'phosphorus': 0.014,
  'riboflavin': 2.5e-05,
  'vitamin b 6': 4.6e-05,
  'molybdenum': 0,
  'cholesterol': 0.0,
  'vitamin b 12': 2e-08,
  'carbohydrate': 3.55,
  'saturated fat': 0.0,
  'pantothenic acid': 0},
 {'fat': 6.0,
  'iron': 0.00395,
  'zinc': 0.0010500000000000002,
  'fiber': 3.8,
  'sugars': 6.25,
  'sodium': 0.458,
  'niacin': 0.004468,
  'folate': 0.000111,
  'copper': 0.000216,
  'biotin': 0,
  'iodine': 0,
  'protein': 9.6,
  'calcium': 0.095,
  'choline': 0.0265,
  'thiamin': 0.00046300000000000003,
  'chloride': 0,
  'selenium': 3.18e-05,
  'chromium': 0,
  'potassium': 0.16,
  'vitamin c': 0.0,
  'magnesium': 0.044,
  'vitamin e': 7.000000000000001e-05,
  'vitamin a': 0.0,
  'manganese': 0,
  'vitamin d': 0.0,
  'vitamin k': 3.1e-06,
  'phosphorus': 0.122,
  'riboflavin': 0.00031,
  'vitamin b 6': 9.2e-05,
  'molybdenum': 0,
  'cholesterol': 0.0,
  'vitamin b 12': 1e-08,
  'carbohydrate': 44.6,
  'saturated fat': 1.39,
  'pantothenic acid': 0},
 {'fat': 32.1,
  'iron': 0.00357,
  'zinc': 0,
  'fiber': 0.0,
  'sugars': 0.0,
  'sodium': 0.714,
  'niacin': 0,
  'folate': 0,
  'copper': 0,
  'biotin': 0,
  'iodine': 0,
  'protein': 17.9,
  'calcium': 350.0,
  'choline': 0,
  'thiamin': 0,
  'chloride': 0,
  'selenium': 0,
  'chromium': 0,
  'potassium': 0,
  'vitamin c': 0,
  'magnesium': 0,
  'vitamin e': 0,
  'vitamin a': 0.0002679,
  'manganese': 0,
  'vitamin d': 0,
  'vitamin k': 0,
  'phosphorus': 0,
  'riboflavin': 0,
  'vitamin b 6': 0,
  'molybdenum': 0,
  'cholesterol': 0.107,
  'vitamin b 12': 0,
  'carbohydrate': 0.0,
  'saturated fat': 21.4,
  'pantothenic acid': 0},
 {'fat': 13.69,
  'iron': 0.0011200000000000001,
  'zinc': 0.00045000000000000004,
  'fiber': 0.5,
  'sugars': 0.2,
  'sodium': 0.395,
  'niacin': 0.0022429999999999998,
  'folate': 2.8e-05,
  'copper': 4.2000000000000004e-05,
  'biotin': 0,
  'iodine': 0,
  'protein': 15.93,
  'calcium': 0.022,
  'choline': 0.0531,
  'thiamin': 0.000216,
  'chloride': 0,
  'selenium': 3.09e-05,
  'chromium': 0,
  'potassium': 0.219,
  'vitamin c': 0.0,
  'magnesium': 0.036000000000000004,
  'vitamin e': 0.0028799999999999997,
  'vitamin a': 3.2e-05,
  'manganese': 0,
  'vitamin d': 4.2999999999999995e-06,
  'vitamin k': 1.2e-05,
  'phosphorus': 0.17,
  'riboflavin': 0.00016,
  'vitamin b 6': 0.00028599999999999996,
  'molybdenum': 0,
  'cholesterol': 0.037,
  'vitamin b 12': 2.3e-07,
  'carbohydrate': 11.72,
  'saturated fat': 2.051,
  'pantothenic acid': 0},
 {'fat': 0.74,
  'iron': 0.0005,
  'zinc': 0.00381,
  'fiber': 0.0,
  'sugars': 0.0,
  'sodium': 0.395,
  'niacin': 0.002747,
  'folate': 5.1e-05,
  'copper': 0.0008139999999999999,
  'biotin': 0,
  'iodine': 0,
  'protein': 17.88,
  'calcium': 0.091,
  'choline': 0.08090000000000001,
  'thiamin': 2.3e-05,
  'chloride': 0,
  'selenium': 4.29e-05,
  'chromium': 0,
  'potassium': 0.259,
  'vitamin c': 0.0033,
  'magnesium': 0.036000000000000004,
  'vitamin e': 0.00184,
  'vitamin a': 1e-06,
  'manganese': 0,
  'vitamin d': 0.0,
  'vitamin k': 3e-07,
  'phosphorus': 0.234,
  'riboflavin': 9.3e-05,
  'vitamin b 6': 0.000156,
  'molybdenum': 0,
  'cholesterol': 0.097,
  'vitamin b 12': 3.33e-06,
  'carbohydrate': 0.0,
  'saturated fat': 0.201,
  'pantothenic acid': 0},
 {'fat': 3.7,
  'iron': 0.0016,
  'zinc': 0.00069,
  'fiber': 4.9,
  'sugars': 0.99,
  'sodium': 0.443,
  'niacin': 0.00043,
  'folate': 2.1e-05,
  'copper': 0.00019600000000000002,
  'biotin': 0,
  'iodine': 0,
  'protein': 5.44,
  'calcium': 0.026000000000000002,
  'choline': 0.016300000000000002,
  'thiamin': 8.999999999999999e-05,
  'chloride': 0,
  'selenium': 7.699999999999999e-06,
  'chromium': 0,
  'potassium': 0.368,
  'vitamin c': 0.0006,
  'magnesium': 0.04,
  'vitamin e': 0.00091,
  'vitamin a': 0.0,
  'manganese': 0,
  'vitamin d': 0.0,
  'vitamin k': 1.6999999999999998e-06,
  'phosphorus': 0.105,
  'riboflavin': 0.0001,
  'vitamin b 6': 0.000115,
  'molybdenum': 0,
  'cholesterol': 0.0,
  'vitamin b 12': 0.0,
  'carbohydrate': 15.89,
  'saturated fat': 0.529,
  'pantothenic acid': 0},
 {'fat': 7.9,
  'iron': 0.00124,
  'zinc': 0.0007800000000000001,
  'fiber': 1.0,
  'sugars': 1.8,
  'sodium': 0.454,
  'niacin': 0.002198,
  'folate': 1.8999999999999998e-05,
  'copper': 7.2e-05,
  'biotin': 0,
  'iodine': 0,
  'protein': 11.8,
  'calcium': 0.043000000000000003,
  'choline': 0.0422,
  'thiamin': 0.000157,
  'chloride': 0,
  'selenium': 2.11e-05,
  'chromium': 0,
  'potassium': 0.185,
  'vitamin c': 0.0159,
  'magnesium': 0.02,
  'vitamin e': 0.00071,
  'vitamin a': 6.599999999999999e-05,
  'manganese': 0,
  'vitamin d': 2e-07,
  'vitamin k': 8.3e-06,
  'phosphorus': 0.155,
  'riboflavin': 0.000105,
  'vitamin b 6': 0.000146,
  'molybdenum': 0,
  'cholesterol': 0.025,
  'vitamin b 12': 4.0399999999999994e-06,
  'carbohydrate': 10.3,
  'saturated fat': 2.22,
  'pantothenic acid': 0},
 {'fat': 28.6,
  'iron': 0,
  'zinc': 0,
  'fiber': 0,
  'sugars': 0,
  'sodium': 0.679,
  'niacin': 0,
  'folate': 0,
  'copper': 0,
  'biotin': 0,
  'iodine': 0,
  'protein': 0.0,
  'calcium': 0,
  'choline': 0,
  'thiamin': 0,
  'chloride': 0,
  'selenium': 0,
  'chromium': 0,
  'potassium': 0,
  'vitamin c': 0,
  'magnesium': 0,
  'vitamin e': 0,
  'vitamin a': 0,
  'manganese': 0,
  'vitamin d': 0,
  'vitamin k': 0,
  'phosphorus': 0,
  'riboflavin': 0,
  'vitamin b 6': 0,
  'molybdenum': 0,
  'cholesterol': 0,
  'vitamin b 12': 2.4999999999999998e-06,
  'carbohydrate': 10.7,
  'saturated fat': 25.0,
  'pantothenic acid': 0},
 {'fat': 0.13,
  'iron': 0.00039000000000000005,
  'zinc': 0.00021,
  'fiber': 0.6,
  'sugars': 30.54,
  'sodium': 0.712,
  'niacin': 0.00023899999999999998,
  'folate': 2e-06,
  'copper': 3.7e-05,
  'biotin': 0,
  'iodine': 0,
  'protein': 0.36,
  'calcium': 0.011,
  'choline': 0.0017,
  'thiamin': 2.3e-05,
  'chloride': 0,
  'selenium': 1.3e-06,
  'chromium': 0,
  'potassium': 0.08700000000000001,
  'vitamin c': 0.0009000000000000001,
  'magnesium': 0.005,
  'vitamin e': 0.0002,
  'vitamin a': 8e-06,
  'manganese': 0,
  'vitamin d': 0.0,
  'vitamin k': 3e-07,
  'phosphorus': 0.009000000000000001,
  'riboflavin': 1.4e-05,
  'vitamin b 6': 3.2e-05,
  'molybdenum': 0,
  'cholesterol': 0.0,
  'vitamin b 12': 0.0,
  'carbohydrate': 60.66,
  'saturated fat': 0.051,
  'pantothenic acid': 0},
 {'fat': 0.0,
  'iron': 0.0,
  'zinc': 0,
  'fiber': 0.8,
  'sugars': 6.4,
  'sodium': 0.24,
  'niacin': 0,
  'folate': 0,
  'copper': 0,
  'biotin': 0,
  'iodine': 0,
  'protein': 0.8,
  'calcium': 0.003,
  'choline': 0,
  'thiamin': 0,
  'chloride': 0,
  'selenium': 0,
  'chromium': 0,
  'potassium': 0.068,
  'vitamin c': 0,
  'magnesium': 0,
  'vitamin e': 0,
  'vitamin a': 0,
  'manganese': 0,
  'vitamin d': 0.0,
  'vitamin k': 0,
  'phosphorus': 0,
  'riboflavin': 0,
  'vitamin b 6': 0,
  'molybdenum': 0,
  'cholesterol': 0.0,
  'vitamin b 12': 0,
  'carbohydrate': 12.8,
  'saturated fat': 0.0,
  'pantothenic acid': 0},
 {'fat': 0.43,
  'iron': 0.00023,
  'zinc': 0.00011,
  'fiber': 1.0,
  'sugars': 0,
  'sodium': 0.808,
  'niacin': 0.000109,
  'folate': 8e-06,
  'copper': 2.6e-05,
  'biotin': 0,
  'iodine': 0,
  'protein': 0.48,
  'calcium': 0.054,
  'choline': 0,
  'thiamin': 4.7000000000000004e-05,
  'chloride': 0,
  'selenium': 0,
  'chromium': 0,
  'potassium': 0.112,
  'vitamin c': 0.0021000000000000003,
  'magnesium': 0.0070999999999999995,
  'vitamin e': 0.00012,
  'vitamin a': 4e-06,
  'manganese': 5.6e-05,
  'vitamin d': 0,
  'vitamin k': 1.68e-05,
  'phosphorus': 0.016,
  'riboflavin': 5.7e-05,

Convert standardized ingredients nutrients data to *Pandas* dataframe:

In [15]:
df: DataFrame = FDC.get_standardized_ingredients_nutrients_dataframe(
    ingredients,
    std_ingredients_nutrients_data,
)

Check `df` *Pandas* dataframe:

In [16]:
df.head()

     fat     iron     zinc  fiber  sugars  sodium    niacin    folate    copper  biotin  iodine  protein  calcium  choline   thiamin  chloride  selenium  chromium  potassium  vitamin c  magnesium  vitamin e  vitamin a  manganese     vitamin d  vitamin k  phosphorus  riboflavin  vitamin b 6  molybdenum  cholesterol  vitamin b 12  carbohydrate  saturated fat  pantothenic acid name
0   2.94  0.00085  0.00000    0.6    0.00   0.418  0.000000  0.000000  0.000000     0.0       0    12.40    0.035   0.0000  0.000000         0  0.000000         0      0.000     0.0035       0.00    0.00000   0.000035        0.0  0.000000e+00        0.0       0.000    0.000000     0.000000           0        0.032  0.000000e+00          5.29          0.590               0.0  cod
1   0.00  0.00000  0.00000    0.0   65.00   0.005  0.000000  0.000000  0.000000     0.0       0     0.00    0.015   0.0000  0.000000         0  0.000000         0      0.105     0.0000       0.00    0.00000   0.000000        0.0  0.000000e+00        0.0       0.000    0.000000     0.000000           0        0.000  0.000000e+00         65.00          0.000               0.0  fig
2  28.80  0.00000  0.00000    3.2   54.50   0.176  0.000000  0.000000  0.000000     0.0       0     6.41    0.128   0.0000  0.000000         0  0.000000         0      0.000     0.0000       0.00    0.00000   0.000000        0.0  0.000000e+00        0.0       0.000    0.000000     0.000000           0        0.032  0.000000e+00         57.70         16.000               0.0  egg
3   0.00  0.00004  0.00004    0.0    0.00   0.001  0.000013  0.000000  0.000021     0.0       0     0.00    0.000   0.0000  0.000006         0  0.000000         0      0.002     0.0000       0.00    0.00000   0.000000        0.0  0.000000e+00        0.0       0.004    0.000004     0.000001           0        0.000  0.000000e+00          0.00          0.000               0.0  gin
4   3.87  0.00084  0.00184    0.0    1.54   1.149  0.006055  0.000001  0.000124     0.0       0    19.04    0.008   0.0756  0.000426         0  0.000034         0      0.371     0.0000       0.02    0.00022   0.000013        0.0  7.000000e-07        0.0       0.276    0.000191     0.000411           0        0.054  4.000000e-07          1.58          1.285               0.0  ham

Create a dictionary for `read_csv()` function calling:

In [17]:
read_csv_params: dict[str, str] = {
    "file": "daily_nutrients_norm.tsv",

    "file_path": "../data/datasets/raw/",
}

Read the file `daily_nutrients_norm.tsv` data to a *Pandas* dataframe:

In [18]:
daily_nutrients_norm: DataFrame = read_csv(
    read_csv_params["file_path"] + read_csv_params["file"],
    sep='\t',
)

Check `daily_nutrients_norm` *Pandas* dataframe:

In [19]:
daily_nutrients_norm.head()

     name  number (g)
0     Fat      78.000
1   Fiber      28.000
2  Sugars      50.000
3    Iron       0.018
4    Zinc       0.011

Transform the values of `df` *Pandas* dataframe into `%` of the daily nutritions norm:

In [20]:
for _, row in daily_nutrients_norm.iterrows():
    df[row["name"].lower()] = round(
        df[row["name"].lower()] * 100 / row["number (g)"],
        3,
    )

Check `df` *Pandas* dataframe:

In [21]:
df

        fat    iron    zinc   fiber  sugars  sodium  niacin  folate  copper  biotin  iodine  protein  calcium  choline  thiamin  chloride  selenium  chromium  potassium  vitamin c  magnesium  vitamin e  vitamin a  manganese  vitamin d  vitamin k  phosphorus  riboflavin  vitamin b 6  molybdenum  cholesterol  vitamin b 12  carbohydrate  saturated fat  pantothenic acid                  name
0     3.769   4.722   0.000   2.143    0.00  18.174   0.000    0.00   0.000     0.0     0.0    24.80    2.692    0.000    0.000       0.0     0.000       0.0      0.000      3.889      0.000      0.000      3.933      0.000        0.0      0.000        0.00       0.000        0.000         0.0       10.667         0.000         1.924          2.950              0.00                   cod
1     0.000   0.000   0.000   0.000  130.00   0.217   0.000    0.00   0.000     0.0     0.0     0.00    1.154    0.000    0.000       0.0     0.000       0.0      2.234      0.000      0.000      0.000      0.000      0.000        0.0      0.000        0.00       0.000        0.000         0.0        0.000         0.000        23.636          0.000              0.00                   fig
2    36.923   0.000   0.000  11.429  109.00   7.652   0.000    0.00   0.000     0.0     0.0    12.82    9.846    0.000    0.000       0.0     0.000       0.0      0.000      0.000      0.000      0.000      0.000      0.000        0.0      0.000        0.00       0.000        0.000         0.0       10.667         0.000        20.982         80.000              0.00                   egg
3     0.000   0.222   0.364   0.000    0.00   0.043   0.081    0.00   2.333     0.0     0.0     0.00    0.000    0.000    0.500       0.0     0.000       0.0      0.043      0.000      0.000      0.000      0.000      0.000        0.0      0.000        0.32       0.308        0.059         0.0        0.000         0.000         0.000          0.000              0.00                   gin
4     4.962   4.667  16.727   0.000    3.08  49.957  37.844    0.25  13.778     0.0     0.0    38.08    0.615   13.745   35.500       0.0    61.455       0.0      7.894      0.000      4.762      1.467      1.444      0.000        3.5      0.000       22.08      14.692       24.176         0.0       18.000        16.667         0.575          6.425              0.00                   ham
..      ...     ...     ...     ...     ...     ...     ...     ...     ...     ...     ...      ...      ...      ...      ...       ...       ...       ...        ...        ...        ...        ...        ...        ...        ...        ...         ...         ...          ...         ...          ...           ...           ...            ...               ...                   ...
298   2.859   0.000   0.000   0.000    0.00  13.217   0.000    0.00   0.000     0.0     0.0    35.80    0.000    0.000    0.000       0.0     0.000       0.0      0.000      1.222      0.000      0.000      0.000      0.000        0.0      0.000        0.00       0.000        0.000         0.0       18.000         0.000         0.975          4.450              0.00       pork tenderloin
299   3.359   0.500   0.727   0.357    0.60  16.913   1.781    0.50   2.111     0.0     0.0     1.42    0.769    0.673    2.000       0.0     0.727       0.0      0.894      0.000      0.714      0.667      0.111      0.000        0.0      0.500        1.60       4.077        1.471         0.0        1.667         0.000         1.924          3.195              0.00       poultry sausage
300   0.000   0.000   0.000   0.000   22.00   0.000   0.000    0.00   0.000     0.0     0.0     0.00    3.231    0.000    0.000       0.0     0.000       0.0      6.191     11.333      0.000      0.000      0.000      0.000       66.0      0.000        0.00       0.000        0.000         0.0        0.000         0.000         4.473          0.000              0.00     pomegranate juice
301   0.013  18.889   1.091   5.714   19.20   0.174   8.125    3.25  15.556     0.0     0.0     4.00    1.077    5.455   16.667       0.0     1.273       0.0      9.128      4.444      4.048      1.267      0.111      2.609        0.0      0.083        6.24       4.615        4.529         0.0        0.000         0.000         6.327          0.000              7.94   jerusalem artichoke
302   3.731   3.333   9.273   8.571    2.94  21.783   0.200    0.25   3.222     0.0     0.0     2.90    0.769    0.618    0.250       0.0     5.273       0.0      0.191      0.333      3.810      1.667      2.333      0.000        0.0      1.167        2.72       0.462        2.118         0.0        1.333         0.000         5.018          5.040              0.00  hominy/cornmeal/masa

[303 rows x 36 columns]

Create a dictionary for `to_csv()` method calling:

In [22]:
to_csv_params: dict[str, str] = {
    "file": "ingredients_nutrients_percentage.csv",

    "file_path": "../data/datasets/processed/",
}

Save the transformed *Pandas* dataframe:

In [23]:
df.to_csv(to_csv_params["file_path"] + to_csv_params["file"], )